/**
 * ForThePeople.in — Your District. Your Data. Your Right.
 * © 2026 Jayanth M B. MIT License with Attribution.
 * https://github.com/jayanthmb14/forthepeople
 */

// ═══════════════════════════════════════════════════════════
// POST /api/admin/cleanup-news
// One-time cleanup: remove stale articles, duplicates, wrong auto-alerts
// Auth: ADMIN_PASSWORD
// ═══════════════════════════════════════════════════════════
import { NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import { requireAdmin } from "@/lib/admin-auth";

export async function POST() {
  const { ok } = await requireAdmin();
  if (!ok) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const results: Record<string, number> = {};

  // 1. Delete news articles older than 7 days
  const sevenDaysAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
  const { count: staleNews } = await prisma.newsItem.deleteMany({
    where: { publishedAt: { lt: sevenDaysAgo } },
  });
  results.staleArticlesDeleted = staleNews;

  // 2. Delete news articles with future publishedAt (RSS parsing errors)
  const { count: futureNews } = await prisma.newsItem.deleteMany({
    where: { publishedAt: { gt: new Date() } },
  });
  results.futureArticlesDeleted = futureNews;

  // 3. Delete duplicate news articles — keep the oldest per district+title prefix
  const allNews = await prisma.newsItem.findMany({
    orderBy: { publishedAt: "asc" },
    select: { id: true, districtId: true, title: true },
  });
  const seen = new Map<string, true>();
  const dupIds: string[] = [];
  for (const article of allNews) {
    const words = article.title.toLowerCase().replace(/[^a-z0-9\s]/g, "").trim().split(/\s+/).filter((w) => w.length > 3);
    const key = `${article.districtId}:${words.slice(0, 5).join(" ")}`;
    if (seen.has(key)) {
      dupIds.push(article.id);
    } else {
      seen.set(key, true);
    }
  }
  if (dupIds.length > 0) {
    const { count: dups } = await prisma.newsItem.deleteMany({ where: { id: { in: dupIds } } });
    results.duplicateArticlesDeleted = dups;
  } else {
    results.duplicateArticlesDeleted = 0;
  }

  // 4. Delete auto-generated alerts older than 7 days (stale from old news)
  const { count: oldAlerts } = await prisma.localAlert.deleteMany({
    where: {
      autoGenerated: true,
      createdAt: { lt: sevenDaysAgo },
    },
  });
  results.staleAutoAlertsDeleted = oldAlerts;

  // 5. Clear NewsActionQueue (will be repopulated from fresh news)
  const { count: queueCleared } = await prisma.newsActionQueue.deleteMany({
    where: { status: { in: ["pending", "skipped"] } },
  });
  results.newsActionQueueCleared = queueCleared;

  // 6. Delete AIInsight records based on stale news (module: news/alerts)
  const { count: staleInsights } = await prisma.aIInsight.deleteMany({
    where: {
      OR: [
        { module: "alerts" },
        { createdAt: { lt: sevenDaysAgo } },
      ],
    },
  });
  results.staleInsightsDeleted = staleInsights;

  return NextResponse.json({
    ok: true,
    results,
    message: "Cleanup complete. Trigger /api/cron/generate-insights to regenerate AI insights.",
  });
}
