/**
 * ForThePeople.in — Your District. Your Data. Your Right.
 * © 2026 Jayanth M B. MIT License.
 * https://github.com/jayanthmb14/forthepeople
 */

// ═══════════════════════════════════════════════════════════
// POST /api/admin/cleanup-news
// One-time cleanup: remove stale articles, duplicates, wrong auto-alerts
// Auth: ADMIN_PASSWORD
// ═══════════════════════════════════════════════════════════
import { NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import { requireAdmin } from "@/lib/admin-auth";
import { planTitleDuplicates } from "@/lib/news-dedupe";

export async function POST() {
  const { ok } = await requireAdmin();
  if (!ok) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const results: Record<string, number> = {};

  // 1. Delete news articles older than 7 days
  const sevenDaysAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
  const { count: staleNews } = await prisma.newsItem.deleteMany({
    where: { publishedAt: { lt: sevenDaysAgo } },
  });
  results.staleArticlesDeleted = staleNews;

  // 2. Delete news articles with future publishedAt (RSS parsing errors)
  const { count: futureNews } = await prisma.newsItem.deleteMany({
    where: { publishedAt: { gt: new Date() } },
  });
  results.futureArticlesDeleted = futureNews;

  // 3. Delete duplicate news articles — per district, the same rule the
  // scrape-news cron uses (planTitleDuplicates: same 50-character title
  // prefix, first fetched stays). The old key kept only ASCII letters, so
  // every Hindi or Kannada headline of a district shared one empty key and
  // all but one would have been deleted.
  const allNews = await prisma.newsItem.findMany({
    select: { id: true, districtId: true, title: true, fetchedAt: true },
  });
  const byDistrict = new Map<string, typeof allNews>();
  for (const article of allNews) {
    const key = article.districtId ?? "";
    const rows = byDistrict.get(key);
    if (rows) rows.push(article);
    else byDistrict.set(key, [article]);
  }
  const dupIds = [...byDistrict.values()].flatMap((rows) => planTitleDuplicates(rows).flatMap((g) => g.removeIds));
  if (dupIds.length > 0) {
    const { count: dups } = await prisma.newsItem.deleteMany({ where: { id: { in: dupIds } } });
    results.duplicateArticlesDeleted = dups;
  } else {
    results.duplicateArticlesDeleted = 0;
  }

  // 4. Delete auto-generated alerts older than 7 days (stale from old news)
  const { count: oldAlerts } = await prisma.localAlert.deleteMany({
    where: {
      autoGenerated: true,
      createdAt: { lt: sevenDaysAgo },
    },
  });
  results.staleAutoAlertsDeleted = oldAlerts;

  // 5. Clear NewsActionQueue (will be repopulated from fresh news). Review
  // items raised by the verification cron (dataType "verify-leaders" and
  // any other "verify-*") are NOT news: they wait for an admin, so they stay.
  const { count: queueCleared } = await prisma.newsActionQueue.deleteMany({
    where: { status: { in: ["pending", "skipped"] }, NOT: { dataType: { startsWith: "verify-" } } },
  });
  results.newsActionQueueCleared = queueCleared;

  // 6. Delete AIInsight records based on stale news (module: news/alerts)
  const { count: staleInsights } = await prisma.aIInsight.deleteMany({
    where: {
      OR: [
        { module: "alerts" },
        { createdAt: { lt: sevenDaysAgo } },
      ],
    },
  });
  results.staleInsightsDeleted = staleInsights;

  return NextResponse.json({
    ok: true,
    results,
    message: "Cleanup complete. Trigger /api/cron/generate-insights to regenerate AI insights.",
  });
}
