// GENERATED by scripts/gen-i18n-namespaces.mjs — do not edit.
// One entry per src/dictionaries/en/<name>.json (page-level messages).
export const PAGE_NAMESPACES: readonly string[] = [
  "page_finance",
  "page_money"
];
