// GENERATED by scripts/gen-i18n-namespaces.mjs — do not edit.
// One entry per src/dictionaries/en/<name>.json (page-level messages).
export const PAGE_NAMESPACES: readonly string[] = [
  "page_about",
  "page_compare",
  "page_contribute",
  "page_contributors",
  "page_features",
  "page_feedback",
  "page_site",
  "page_state",
  "page_support",
  "page_taluk",
  "page_village",
  "page_vote"
];
