/**
 * ForThePeople.in — Your District. Your Data. Your Right.
 * © 2026 Jayanth M B. MIT License.
 *
 * Land & water rows the September 2026 audit found wrong, invented or not
 * checkable (crop prices, alerts, dam names). Rule: verified or hidden.
 * Nothing here writes a new figure: rows are hidden (LocalAlert.active =
 * false), deleted when the whole row is unfounded or cannot be checked
 * (CropPrice has no "active" flag), or a name is changed to the one
 * canonical spelling already used by the code (CANONICAL_DAMS).
 *
 * The code fixes that stop these rows coming back are in the same branch:
 * SHOWN_CROP_PRICE / shownCropPrices / OFFICIAL_ALERTS (src/lib/data-filters.ts),
 * the AGMARKNET checks (src/scraper/lib/agmarknet.ts), the news pipeline
 * (src/lib/news-action-engine.ts no longer writes LocalAlert) and the dam
 * collector (src/scraper/jobs/dams.ts writes the canonical name).
 *
 * DRY RUN by default: prints every change (table, id, field, current → new,
 * source) and exits. Pass --confirm to apply, all in ONE transaction.
 *
 *   npx tsx scripts/fix-audit-2026-09-land-water.ts            # dry run
 *   npx tsx scripts/fix-audit-2026-09-land-water.ts --confirm  # apply
 *
 * Rows are matched by id. Each fix lists the values seen on the check day
 * (`was`); a row whose value changed since then is skipped and flagged
 * (look at it by hand). A row already gone, or already holding the new
 * value, is skipped. Deletes run as one deleteMany per table; the whole run
 * rolls back if a table deletes a different number of rows than planned.
 */
import "./_env";
import { PrismaClient } from "../src/generated/prisma";
import { PrismaPg } from "@prisma/adapter-pg";

const CONFIRM = process.argv.includes("--confirm");
const CHECKED = "2026-09-28";

type Table = "CropPrice" | "LocalAlert" | "DamReading";
type Value = string | number | boolean | null;

interface Fix {
  table: Table;
  id: string;
  /** update = new values; hide = LocalAlert.active → false; delete = remove the row. */
  op: "update" | "hide" | "delete";
  set?: Record<string, Value>;
  /** Values seen on the check day; any other current value = changed since check → skipped. */
  was: Record<string, Value>;
  /** Audit finding index (land-water.json) and a short label. */
  finding: number;
  label: string;
  why: string;
  source: string;
}

const SEED_WHY =
  "Invented seed row (prisma/seed.ts '9. Crop Prices'), labelled 'AGMARKNET / data.gov.in' with the seed run's date; shown as a real mandi price.";
const SEED_SRC = "prisma/seed.ts (git history, section 9) + http://localhost:3000/api/data/crops?state=karnataka&district=mandya (fetchedAt 2026-03-17, arrivalQty set)";
const seed = (id: string, commodity: string, market: string, modalPrice: number, arrivalQty: number): Fix => ({
  table: "CropPrice",
  id,
  op: "delete",
  was: { commodity, market, modalPrice, arrivalQty, source: "AGMARKNET / data.gov.in" },
  finding: 1,
  label: `Mandya · seed ${commodity} @ ${market}`,
  why: SEED_WHY,
  source: SEED_SRC,
});

const BANTHARA_WHY =
  "Banthara APMC 22 Jun 2026 row with a placeholder-looking max of 50,000 and an odd average; about 3× the Tur MSP and more than processed dal the same day. Cannot be checked against AGMARKNET (97 days old); hidden as a source outlier.";
const BANTHARA_SRC = "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2260617 (Tur MSP ₹8,450/qtl 2026-27) + http://localhost:3000/api/data/crops?state=uttar-pradesh&district=lucknow";
const banthara = (id: string, commodity: string, minPrice: number, maxPrice: number, modalPrice: number): Fix => ({
  table: "CropPrice",
  id,
  op: "delete",
  was: { commodity, market: "Banthara APMC", minPrice, maxPrice, modalPrice },
  finding: 8,
  label: `Lucknow · ${commodity} @ Banthara APMC, 22 Jun`,
  why: BANTHARA_WHY,
  source: BANTHARA_SRC,
});

const NEWS_WHY =
  "A news story stored as a 'warning in force' by the news pipeline (autoGenerated). Not an official warning (IMD / NDMA SACHET); the story stays on the news page.";
const newsAlert = (id: string, district: string, title: string, finding = 12): Fix => ({
  table: "LocalAlert",
  id,
  op: "hide",
  set: { active: false },
  was: { title, autoGenerated: true, active: true },
  finding,
  label: `${district} · news item shown as a warning: "${title}"`,
  why: NEWS_WHY,
  source: `http://localhost:3000/api/data/alerts?district=${district.toLowerCase().replace(/ /g, "-")}`,
});

const FIXES: Fix[] = [
  // ── Finding 1: invented Mandya seed prices (8 rows) ─────────────────────
  seed("cmmv9nbli003zubxntuqy70rk", "Sugarcane", "Mandya APMC", 330, 12500),
  seed("cmmv9nbn70040ubxnk6jxvoeg", "Paddy", "Maddur APMC", 2250, 850),
  seed("cmmv9nbou0041ubxnksr4drtk", "Ragi", "Nagamangala", 3700, 420),
  seed("cmmv9nbqi0042ubxnnncz6szl", "Maize", "K R Pete", 1950, 320),
  seed("cmmv9nbs30043ubxnaecwm86m", "Areca", "Mandya APMC", 35000, 45),
  seed("cmmv9nbtn0044ubxnlula46fs", "Coconut", "Srirangapatna", 9800, 180),
  seed("cmmv9nbv80045ubxnmjwhbexf", "Banana", "Maddur APMC", 1400, 95),
  seed("cmmv9nbwt0046ubxn1gwzhilo", "Tomato", "Mandya APMC", 800, 220),

  // ── Finding 8: implausible Banthara APMC rows (Lucknow, 22 Jun) ─────────
  banthara("cmqq37b9h004904l321bogmrb", "Red gram/Arhar/Tur(whole)", 8150, 50000, 25069.14),
  banthara("cmqq378g6003j04l3n1awtkcm", "Peas(Dry)", 2900, 50000, 19690.08),
  banthara("cmqq378jx003k04l36xggxbwf", "Gram Raw(Chholia)", 5000, 50000, 17941.23),
  banthara("cmqq37bmh004c04l3lt9fof0r", "Black Gram Dal(Urd Dal)", 6500, 50000, 14451.54),
  banthara("cmqq37aon004404l3eocftlhr", "Green Gram(Moong)(Whole)", 8000, 50000, 12761.61),
  {
    ...banthara("cmqq37814003f04l35kty1oxi", "Coriander(Leaves)", 19523, 19523, 19523),
    why: "Same Banthara 22 Jun batch: a flat 19,523 (min = max = modal), three times Lucknow APMC's 6,374.73 the same day. Cannot be checked; hidden as a source outlier.",
  },

  // ── Finding 9: Nanjangud potato 6,666 (shown '₹67/kg, up 140%') ─────────
  {
    table: "CropPrice",
    id: "cmo31usf807vj10mv9l958san",
    op: "delete",
    was: { commodity: "Potato", market: "Nanjangud APMC", minPrice: 6666, maxPrice: 6750, modalPrice: 6666 },
    finding: 9,
    label: "Mysuru · Potato @ Nanjangud APMC, 17 Apr",
    why: "₹66.66/kg the day after ₹27.77/kg, 4–5× Bangalore APMC (₹13/kg) the same week; repeating digits look like a per-bag conversion. Cannot be checked; hidden as a source outlier (it headlined the page as 'up 140%').",
    source: "http://localhost:3000/api/data/crops?state=karnataka&district=mysuru and ?district=bengaluru-urban",
  },

  // ── Finding 12: news stories shown as 'warnings in force' → hidden ──────
  newsAlert("cmuk1dvby000u2yxn9xkle9ll", "Chennai", "Aarthi Scans & Labs Ranked #1 in Diagnostics"),
  newsAlert("cmuk1fq2b001a2yxncm63gtw3", "Chennai", "Action sought against CM Vijay and minister Aadhav Arjuna for violating model code of conduct"),
  newsAlert("cmuk1og6b00432yxnrgzebsap", "Hyderabad", "Organ donation saves lives in Hyderabad"),
  newsAlert("cmuk1sdpy00582yxn59l9ohzq", "Hyderabad", "Childhood Cancer Survivors Awareness Programme in Hyderabad"),
  newsAlert("cmuk1y4aa00722yxnouqukyxh", "Kolkata", "Opposition unity sought for removal of CEC Gyanesh Kumar"),
  newsAlert("cmuk20qmd008l2yxnun3zzk9j", "Mumbai", "ECI eases SIR notice process"),
  newsAlert("cmuk21xk8008x2yxnfw1jssfv", "Mumbai", "Allegation of ECI 'match-fixing' in Maharashtra assembly elections"),
  newsAlert("cmuk222p000902yxnzo94vju2", "Mumbai", "Health screening campaign"),
  newsAlert("cmuk23c0l009c2yxn6sjho1la", "Mumbai", "Maharashtra to revive student elections after 33-year hiatus"),
  newsAlert("cmuk23htt009f2yxnbfa4dar2", "Mumbai", "Chemical leak in Mumbai public toilet"),

  // ── Findings 13–15: news 'warnings' with wrong facts / a duplicate → deleted ──
  {
    table: "LocalAlert",
    id: "cmuk1woeg006j2yxnny49gkoo",
    op: "delete",
    was: { title: "Claim of 27 lakh voter deletions in West Bengal", autoGenerated: true, active: true },
    finding: 13,
    label: "Kolkata · 'Chief Minister Mamata Banerjee' alert",
    why: "AI summary calls Mamata Banerjee 'Chief Minister'; Suvendu Adhikari has been CM since 9 May 2026. A news item, not a warning.",
    source: "https://newsonair.gov.in/suvendu-adhikari-to-take-oath-as-first-bjp-cm-of-west-bengal-today/",
  },
  {
    table: "LocalAlert",
    id: "cmuk1z25s00872yxn8mqp1e1k",
    op: "delete",
    was: { title: "Maharashtra SIR deadline extended", autoGenerated: true, active: true },
    finding: 14,
    label: "Mumbai · 'State Implementation Report (SIR)' alert",
    why: "SIR is the Election Commission's Special Intensive Revision of electoral rolls, not a 'State Implementation Report'; the 12 Oct date is unverified. A news item, not a warning.",
    source: "https://pune.gov.in/en/sir-2026/ ; https://www.aninews.in/news/national/general-news/eci-revises-special-intensive-revision-schedule-of-electoral-rolls-in-delhi-maharashtra20260926195800/",
  },
  {
    table: "LocalAlert",
    id: "cmuk20wpp008o2yxnwkklk98m",
    op: "delete",
    was: { title: "Suspected chemical exposure deaths in Mumbai public toilet", autoGenerated: true, active: true },
    finding: 15,
    label: "Mumbai · duplicate of 'Chemical leak in Mumbai public toilet'",
    why: "The same 27 Sep incident as cmuk23htt009f2yxnbfa4dar2 under a reworded headline (counted twice in '7 warnings'). A news item, not a warning.",
    source: "http://localhost:3000/api/data/alerts?state=maharashtra&district=mumbai",
  },

  // ── Finding 25: one name for KRS everywhere (CANONICAL_DAMS) ────────────
  {
    table: "DamReading",
    id: "cmuk1bma5000g2yxnszirddnz",
    op: "update",
    set: { damName: "Krishna Raja Sagara (KRS)" },
    was: { damName: "KRS Dam (Krishnaraja Sagara)" },
    finding: 25,
    label: "Mysuru · KRS reading name",
    why: "Mysuru's KRS row kept an old seed spelling; Mandya and Bengaluru Urban use the canonical 'Krishna Raja Sagara (KRS)'. Figures unchanged.",
    source: "src/scraper/lib/dams.ts CANONICAL_DAMS; portal https://water.karnataka.gov.in ('K.R.Sagara Dam')",
  },
  {
    table: "DamReading",
    id: "cmuk1blyb000f2yxnactoj51x",
    op: "update",
    set: { damNameLocal: "ಕೃಷ್ಣರಾಜ ಸಾಗರ" },
    was: { damNameLocal: "ಕೃಷ್ಣರಾಜಸಾಗರ" },
    finding: 25,
    label: "Mandya · KRS Kannada name",
    why: "Mandya's KRS row spelt the Kannada name without the space; Mysuru and Bengaluru Urban use the canonical 'ಕೃಷ್ಣರಾಜ ಸಾಗರ'.",
    source: "src/scraper/lib/dams.ts CANONICAL_DAMS",
  },
];

/** Prisma delegate name for a table ("CropPrice" → "cropPrice"). */
const delegateName = (table: string) => table[0].toLowerCase() + table.slice(1);

function same(current: unknown, planned: Value): boolean {
  if (current === null || current === undefined) return planned === null;
  if (planned === null) return false;
  if (typeof planned === "number") return Math.abs(Number(current) - planned) < 1e-6;
  if (typeof planned === "boolean") return current === planned;
  return String(current) === String(planned);
}

function show(v: unknown): string {
  if (v === null || v === undefined) return "null";
  if (v instanceof Date) return v.toISOString();
  if (typeof v === "string") return JSON.stringify(v.length > 70 ? v.slice(0, 67) + "…" : v);
  return String(v);
}

interface Planned {
  fix: Fix;
  data?: Record<string, Value>;
}

async function main() {
  // Guard: every row appears once, so two fixes never fight over it.
  const seen = new Set<string>();
  for (const f of FIXES) {
    const key = `${f.table}:${f.id}`;
    if (seen.has(key)) throw new Error(`Duplicate fix for ${key}`);
    seen.add(key);
    if ((f.op === "update" || f.op === "hide") && (!f.set || Object.keys(f.set).length === 0)) throw new Error(`No fields to set: ${key}`);
    if (f.op === "hide" && f.table !== "LocalAlert") throw new Error(`Only LocalAlert has an active flag: ${key}`);
  }

  const p = new PrismaClient({ adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL! }) });
  const plan: Planned[] = [];
  const counts: Record<string, { update: number; hide: number; delete: number; done: number; gone: number; drift: number }> = {};
  const tally = (t: string) => (counts[t] ??= { update: 0, hide: 0, delete: 0, done: 0, gone: 0, drift: 0 });

  try {
    console.log(`Land & water audit fixes (checked ${CHECKED}) — ${CONFIRM ? "APPLYING" : "DRY RUN"}`);
    let currentTable = "";
    for (const f of FIXES) {
      if (f.table !== currentTable) {
        currentTable = f.table;
        console.log(`\n══ ${f.table} ══`);
      }
      const rows = (await p.$queryRawUnsafe(`SELECT * FROM "${f.table}" WHERE id = $1`, f.id)) as Array<Record<string, unknown>>;
      const row = rows[0];
      const verb = f.op === "delete" ? "DELETE" : f.op === "hide" ? "HIDE (active → false)" : "UPDATE";
      console.log(`\n• ${verb} ${f.table} ${f.id} — finding #${f.finding}: ${f.label}`);
      console.log(`  why:    ${f.why}`);
      console.log(`  source: ${f.source}`);
      if (!row) {
        console.log("  → row not found (already deleted?) — skipped");
        tally(f.table).gone++;
        continue;
      }
      // Changed since the check? Compare every value we saw.
      const drifted = Object.entries(f.was).filter(([field, v]) => {
        if (!(field in row)) throw new Error(`${f.table}.${field} does not exist (fix ${f.id})`);
        // A field already holding the planned new value is not drift.
        if (f.set && field in f.set && same(row[field], f.set[field])) return false;
        return !same(row[field], v);
      });
      if (drifted.length > 0) {
        for (const [field, v] of drifted) console.log(`    ${field}: now ${show(row[field])}, was ${show(v)} on ${CHECKED} — CHANGED SINCE CHECK`);
        console.log("  → skipped; review by hand");
        tally(f.table).drift++;
        continue;
      }
      if (f.op === "delete") {
        for (const [field] of Object.entries(f.was)) console.log(`    ${field}: ${show(row[field])}`);
        console.log("  → delete whole row");
        plan.push({ fix: f });
        tally(f.table).delete++;
        continue;
      }
      const data: Record<string, Value> = {};
      for (const [field, planned] of Object.entries(f.set!)) {
        if (!(field in row)) throw new Error(`${f.table}.${field} does not exist (fix ${f.id})`);
        if (same(row[field], planned)) {
          console.log(`    ${field}: ${show(row[field])} (already ${show(planned)})`);
          continue;
        }
        console.log(`    ${field}: ${show(row[field])} → ${show(planned)}`);
        data[field] = planned;
      }
      if (Object.keys(data).length === 0) {
        console.log("  → already applied — skipped");
        tally(f.table).done++;
        continue;
      }
      plan.push({ fix: f, data });
      tally(f.table)[f.op === "hide" ? "hide" : "update"]++;
    }

    console.log("\n══ Summary ══");
    for (const [t, c] of Object.entries(counts)) {
      console.log(
        `${t.padEnd(12)} update ${String(c.update).padStart(2)}   hide ${String(c.hide).padStart(2)}   delete ${String(c.delete).padStart(2)}   already done ${String(c.done).padStart(2)}   not found ${String(c.gone).padStart(2)}   changed-since-check ${String(c.drift).padStart(2)}`,
      );
    }
    console.log(`Total changes to apply: ${plan.length}`);

    if (!CONFIRM) {
      console.log("\nDry run only. Re-run with --confirm to apply (one transaction).");
      return;
    }
    if (plan.length === 0) {
      console.log("Nothing to do.");
      return;
    }
    type Delegate = {
      update: (a: unknown) => Promise<unknown>;
      deleteMany: (a: unknown) => Promise<{ count: number }>;
    };
    const deletesByTable = new Map<string, string[]>();
    for (const { fix } of plan) {
      if (fix.op !== "delete") continue;
      deletesByTable.set(fix.table, [...(deletesByTable.get(fix.table) ?? []), fix.id]);
    }
    await p.$transaction(
      async (tx) => {
        const model = (table: string) => (tx as unknown as Record<string, Delegate>)[delegateName(table)];
        for (const { fix, data } of plan) {
          if (fix.op !== "delete") await model(fix.table).update({ where: { id: fix.id }, data });
        }
        for (const [table, ids] of deletesByTable) {
          const { count } = await model(table).deleteMany({ where: { id: { in: ids } } });
          if (count !== ids.length) throw new Error(`${table}: expected to delete ${ids.length} rows, deleted ${count} — rolled back`);
        }
      },
      { timeout: 120_000, maxWait: 30_000 },
    );
    console.log(`\nDone: applied ${plan.length} changes in one transaction.`);
    console.log("Clear the Redis caches (admin → Cache) so the crops, alerts and water pages pick this up at once.");
  } finally {
    await p.$disconnect();
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
