/**
 * PoliceStation fixes (checked 27 Sep 2026). Rule: verified or hidden.
 *
 * Karnataka: real numbers from the official pages — Mysuru City Police and
 * Mysuru District Police station pages, the Mandya District Police contact
 * table, and the Karnataka State Police statewide directory
 * (ksp.karnataka.gov.in/ksp_contact) for Bengaluru. Stations that appear in
 * none of them (or belong to another district) are deleted; duplicates from
 * two seed batches are deleted.
 * Other districts: no official directory could be read, and the seed numbers
 * are unsourced (most follow a made-up round-number pattern), so every number
 * is set to null ("hidden: unverifiable"). Station names are kept.
 */
import type { Fix } from "./types";

const CHECKED = "2026-09-27";

export const POLICE_FIXES: Fix[] = [
  {
    table: "PoliceStation", id: "cmmvn778w00nqmuxnb78epadf", op: "update",
    label: "Mysuru · Devaraja Police Station",
    set: { phone: "0821-2418306", email: "devarajamyc@ksp.gov.in" },
    was: { phone: "0821-2443344", email: null },
    why: "Invented number 0821-2443344; Mysuru City Police lists 0821-2418306.",
    source: "https://mysurucitypolice.karnataka.gov.in/27/devaraja-police-station/en", says: "Station page: Ph. No. 0821-2418306, e-mail devarajamyc@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn778w00nwmuxnoo4wya3r", op: "update",
    label: "Mysuru · Hebbal Police Station (Mysuru)",
    set: { phone: "0821-2418318", email: "hebbalmyc@ksp.gov.in" },
    was: { phone: "0821-2483100", email: null },
    why: "Invented number 0821-2483100; Mysuru City Police lists 0821-2418318.",
    source: "https://mysurucitypolice.karnataka.gov.in/40/hebbal-police-station/en", says: "Station page: Ph. No. 0821-2418318, e-mail hebbalmyc@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn778w00ntmuxnvtltwb9f", op: "update",
    label: "Mysuru · Jayalakshmipuram Police Station",
    set: { phone: "0821-2418516", email: "jailaxmipurammyc@ksp.gov.in" },
    was: { phone: "0821-2443377", email: null },
    why: "Invented number 0821-2443377; Mysuru City Police lists 0821-2418516.",
    source: "https://mysurucitypolice.karnataka.gov.in/38/jayalakshmipuram-police-station/en", says: "Station page: Ph. No. 0821-2418516, e-mail jailaxmipurammyc@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn778w00nrmuxnlnxn6uyg", op: "update",
    label: "Mysuru · Krishnaraja Police Station",
    set: { phone: "0821-2418119", email: "krishnarajamyc@ksp.gov.in" },
    was: { phone: "0821-2443355", email: null },
    why: "Invented number 0821-2443355; Mysuru City Police lists 0821-2418119.",
    source: "https://mysurucitypolice.karnataka.gov.in/41/krishnaraja-police-station/en", says: "Station page: Ph. No. 0821-2418119, e-mail krishnarajamyc@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn778w00nzmuxn74l6ezmj", op: "update",
    label: "Mysuru · Lashkar Police Station",
    set: { phone: "0821-2418307", email: "lashkarmyc@ksp.gov.in" },
    was: { phone: "0821-2434100", email: null },
    why: "Invented number 0821-2434100; Mysuru City Police lists 0821-2418307.",
    source: "https://mysurucitypolice.karnataka.gov.in/28/lashkar-police-station/en", says: "Station page: Ph. No. 0821-2418307, e-mail lashkarmyc@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn778w00o0muxnk95dpjfx", op: "update",
    label: "Mysuru · Mandi Mohalla Police Station",
    set: { phone: "0821-2418313", email: "mandimyc@ksp.gov.in" },
    was: { phone: "0821-2432100", email: null },
    why: "Invented number 0821-2432100; Mysuru City Police lists 0821-2418313.",
    source: "https://mysurucitypolice.karnataka.gov.in/35/mandi-police-station/en", says: "Station page: Ph. No. 0821-2418313, e-mail mandimyc@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn778w00nsmuxncyvaapa0", op: "update",
    label: "Mysuru · Nazarbad Police Station",
    set: { phone: "0821-2418308", email: "nazarbadmyc@ksp.gov.in" },
    was: { phone: "0821-2443366", email: null },
    why: "Invented number 0821-2443366; Mysuru City Police lists 0821-2418308.",
    source: "https://mysurucitypolice.karnataka.gov.in/30/nazarbad-police-station/en", says: "Station page: Ph. No. 0821-2418308, e-mail nazarbadmyc@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn778w00o2muxn6b0wexdj", op: "update",
    label: "Mysuru · Saraswathipuram Police Station",
    set: { phone: "0821-2418123", email: "saraswathipurammyc@ksp.gov.in" },
    was: { phone: "0821-2518100", email: null },
    why: "Invented number 0821-2518100; Mysuru City Police lists 0821-2418123.",
    source: "https://mysurucitypolice.karnataka.gov.in/45/sarswarthipuram-police-station/en", says: "Station page: Ph. No. 0821-2418123, e-mail saraswathipurammyc@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn778w00o1muxnh49k7cr5", op: "update",
    label: "Mysuru · Udayagiri Police Station",
    set: { phone: "0821-2418309", email: "udayagirimyc@ksp.gov.in" },
    was: { phone: "0821-2486100", email: null },
    why: "Invented number 0821-2486100; Mysuru City Police lists 0821-2418309.",
    source: "https://mysurucitypolice.karnataka.gov.in/31/udayagiri-police-station/en", says: "Station page: Ph. No. 0821-2418309, e-mail udayagirimyc@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn778w00nymuxnicqogee2", op: "update",
    label: "Mysuru · V.V. Puram Police Station",
    set: { phone: "0821-2418314", email: "vvpurammyc@ksp.gov.in" },
    was: { phone: "0821-2430100", email: null },
    why: "Invented number 0821-2430100; Mysuru City Police lists 0821-2418314.",
    source: "https://mysurucitypolice.karnataka.gov.in/36/vanivilasa-puram-police-station/en", says: "Station page: Ph. No. 0821-2418314, e-mail vvpurammyc@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn778w00numuxnldt081o0", op: "update",
    label: "Mysuru · Vidyaranyapuram Police Station",
    set: { phone: "0821-2418122", email: "vidyaranyamyc@ksp.gov.in" },
    was: { phone: "0821-2443388", email: null },
    why: "Invented number 0821-2443388; Mysuru City Police lists 0821-2418122.",
    source: "https://mysurucitypolice.karnataka.gov.in/44/vidyaranyapuram-police-station/en", says: "Station page: Ph. No. 0821-2418122, e-mail vidyaranyamyc@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn778w00oemuxnsv0ecudt", op: "update",
    label: "Mysuru · Bannur Police Station",
    set: { phone: "08227-275632", email: "bannurmys@ksp.gov.in" },
    was: { phone: "0821-2580100", email: null },
    why: "Invented number 0821-2580100; Mysuru District Police lists 08227-275632.",
    source: "https://mysurupolice.karnataka.gov.in/54/bannuru-police-station/en", says: "Station page: 08227275632, e-mail bannurmys@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn778w00oamuxn74knjb7g", op: "update",
    label: "Mysuru · H.D. Kote Police Station",
    set: { phone: "08228-255329", email: "hdkotemys@ksp.gov.in" },
    was: { phone: "08228-252100", email: null },
    why: "Invented number 08228-252100; Mysuru District Police lists 08228-255329.",
    source: "https://mysurupolice.karnataka.gov.in/44/h-d-kote-police-station/en", says: "Station page: 08228255329, e-mail hdkotemys@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn778w00o8muxn5sgp4v58", op: "update",
    label: "Mysuru · Hunsur Rural Police Station",
    set: { phone: "08222-252042", email: "hunsurruralmys@ksp.gov.in" },
    was: { phone: "08222-252200", email: null },
    why: "Invented number 08222-252200; Mysuru District Police lists 08222-252042.",
    source: "https://mysurupolice.karnataka.gov.in/41/hunasuru-rural-police-station/en", says: "Station page: 08222252042, e-mail hunsurruralmys@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn778w00o7muxncpwjv626", op: "update",
    label: "Mysuru · Hunsur Town Police Station",
    set: { phone: "08222-253133", email: "hunsurtownmys@ksp.gov.in" },
    was: { phone: "08222-252100", email: null },
    why: "Invented number 08222-252100; Mysuru District Police lists 08222-253133.",
    source: "https://mysurupolice.karnataka.gov.in/42/hunasuru-town-police-station/en", says: "Station page: 08222253133, e-mail hunsurtownmys@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn778w00o3muxnsf8qjr0o", op: "update",
    label: "Mysuru · K.R. Nagar Police Station",
    set: { phone: "08223-263666", email: "krnagarmys@ksp.gov.in" },
    was: { phone: "08222-252100", email: null },
    why: "Invented number 08222-252100; Mysuru District Police lists 08223-263666.",
    source: "https://mysurupolice.karnataka.gov.in/37/k-r-nagara-police-station/en", says: "Station page: 08223263666, e-mail krnagarmys@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn778w00o6muxnqvj8f6fo", op: "update",
    label: "Mysuru · Nanjangud Rural Police Station",
    set: { phone: "08221-226259", email: "nanjangudruralmys@ksp.gov.in" },
    was: { phone: "08221-228200", email: null },
    why: "Invented number 08221-228200; Mysuru District Police lists 08221-226259.",
    source: "https://mysurupolice.karnataka.gov.in/48/nanjangud-rural-police-station/en", says: "Station page: 08221226259, e-mail nanjangudruralmys@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn778w00o5muxnct8zd4uf", op: "update",
    label: "Mysuru · Nanjangud Town Police Station",
    set: { phone: "08221-228383", email: "nanjangudtownmys@ksp.gov.in" },
    was: { phone: "08221-228100", email: null },
    why: "Invented number 08221-228100; Mysuru District Police lists 08221-228383.",
    source: "https://mysurupolice.karnataka.gov.in/49/nanjangud-town-police-station/en", says: "Station page: 08221228383, e-mail nanjangudtownmys@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn778w00ocmuxn7yzvb4f2", op: "update",
    label: "Mysuru · Periyapatna Police Station",
    set: { phone: "08223-273100", email: "periyapatnamys@ksp.gov.in" },
    was: { phone: "08222-263100", email: null },
    why: "Invented number 08222-263100; Mysuru District Police lists 08223-273100.",
    source: "https://mysurupolice.karnataka.gov.in/40/periyapattana-police-station/en", says: "Station page: 08223273100, e-mail periyapatnamys@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn778w00o9muxnswfj73wy", op: "update",
    label: "Mysuru · T. Narasipur Police Station",
    set: { phone: "08227-261227", email: "tnpuramys@ksp.gov.in" },
    was: { phone: "08227-262100", email: null },
    why: "Invented number 08227-262100; Mysuru District Police lists 08227-261227.",
    source: "https://mysurupolice.karnataka.gov.in/53/t-narsipura-police-station/en", says: "Station page: 08227261227, e-mail tnpuramys@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmv9ncn1004mubxnaltpxdiq", op: "update",
    label: "Mandya · Maddur Police Station",
    set: { phone: "08232-232170", email: "maddurmdy@ksp.gov.in" },
    was: { phone: "08232-252100", email: null },
    why: "Invented number 08232-252100; Mandya District Police lists Maddur PS as 08232-232170.",
    source: "https://mandyapolice.karnataka.gov.in/55/mandya-district-police-officers-contact-details/en", says: "Maddur PS | 08232-232170 | maddurmdy@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmv9nctc004qubxnqhkfpop0", op: "update",
    label: "Mandya · Pandavapura Police Station",
    set: { phone: "08236-255132", email: "ppuramdy@ksp.gov.in" },
    was: { phone: "08232-258200", email: null },
    why: "Invented number 08232-258200; Mandya District Police lists Pandavapura PS as 08236-255132.",
    source: "https://mandyapolice.karnataka.gov.in/55/mandya-district-police-officers-contact-details/en", says: "Pandavapura PS | 08236-255132 | ppuramdy@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmv9ncok004nubxnqkwjrbjx", op: "update",
    label: "Mandya · Srirangapatna Police Station",
    set: { phone: "08236-252027", email: "srpatnamdy@ksp.gov.in" },
    was: { phone: "08236-252200", email: null },
    why: "Invented number 08236-252200; Mandya District Police lists Srirangapatna Town PS as 08236-252027.",
    source: "https://mandyapolice.karnataka.gov.in/55/mandya-district-police-officers-contact-details/en", says: "Srirangapatna Town PS | 08236-252027 | srpatnamdy@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmv9ncrs004pubxnt4h4pa03", op: "update",
    label: "Mandya · K R Pete Police Station",
    set: { phone: "08230-262248", email: "krpettownmdy@ksp.gov.in", name: "K R Pete Town Police Station" },
    was: { phone: "08232-262200", email: null, name: "K R Pete Police Station" },
    why: "Invented number 08232-262200; Mandya District Police lists K.R. Pet Town PS as 08230-262248. The taluk has separate Town and Rural stations; this row is the town one.",
    source: "https://mandyapolice.karnataka.gov.in/55/mandya-district-police-officers-contact-details/en", says: "K.R. Pet Town PS | 08230-262248 | krpettownmdy@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmv9ncq7004oubxn7cyhfy6p", op: "update",
    label: "Mandya · Malavalli Police Station",
    set: { phone: "08231-242244", email: "malavallitownmdy@ksp.gov.in", name: "Malavalli Town Police Station" },
    was: { phone: "08232-272100", email: null, name: "Malavalli Police Station" },
    why: "Invented number 08232-272100; Mandya District Police lists Malavalli Town PS as 08231-242244. The taluk has separate Town and Rural stations; this row is the town one.",
    source: "https://mandyapolice.karnataka.gov.in/55/mandya-district-police-officers-contact-details/en", says: "Malavalli Town PS | 08231-242244 | malavallitownmdy@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmv9ncux004rubxnu7600mcv", op: "update",
    label: "Mandya · Nagamangala Police Station",
    set: { phone: "08234-286040", email: "nmangalamdy@ksp.gov.in", name: "Nagamangala Town Police Station" },
    was: { phone: "08234-252100", email: null, name: "Nagamangala Police Station" },
    why: "Invented number 08234-252100; Mandya District Police lists Nagamangala Town PS as 08234-286040. The taluk has separate Town and Rural stations; this row is the town one.",
    source: "https://mandyapolice.karnataka.gov.in/55/mandya-district-police-officers-contact-details/en", says: "Nagamangala Town PS | 08234-286040 | nmangalamdy@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn778w00nvmuxn5zzxhhrt", op: "delete",
    label: "Mysuru · Bogadi Police Station (Bogadi, Mysuru 570026)",
    why: "Hidden: unverifiable. No 'Bogadi' station in Mysuru City Police's list or the KSP directory; its phone 0821-2443399 was invented.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn778w00nxmuxnmoaq2cp6", op: "delete",
    label: "Mysuru · Chamundipuram Police Station (Chamundipuram, Mysuru 570004)",
    why: "Hidden: unverifiable. No 'Chamundipuram' station in Mysuru City Police's list or the KSP directory; its phone 0821-2441100 was invented.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn778w00odmuxnict8u86a", op: "delete",
    label: "Mysuru · K.R. Nagar Town Police Station (K.R. Nagar, Mysuru Dist 571602)",
    why: "Hidden: unverifiable. Only one K.R. Nagara station exists (kept on the other row); no separate 'Town' station; its phone 08222-252300 was invented.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn778w00obmuxnjn685l0c", op: "delete",
    label: "Mysuru · Nagarahole Forest Police Station (Nagarahole, H.D. Kote, 571118)",
    why: "Hidden: unverifiable. No 'Nagarahole Forest' police station in Mysuru District Police's list or the KSP directory; its phone 08228-252200 was invented.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn778w00o4muxny478im8t", op: "delete",
    label: "Mysuru · Rural Police Station Mysuru (Bannur Road, Mysuru 570015)",
    why: "Hidden: unverifiable. No 'Rural Police Station Mysuru' in either official list; its phone 0821-2440100 was invented.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmv9ncl2004lubxn76re2an2", op: "delete",
    label: "Mandya · Mandya Town Police Station (Station Road, Mandya)",
    why: "Hidden: unverifiable. Mandya town has Central, East, West, Rural, Traffic and Women stations — no single 'Mandya Town' station; its phone 08232-222600 was invented.",
    source: "https://mandyapolice.karnataka.gov.in/55/mandya-district-police-officers-contact-details/en", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6pu4005rmuxna4six1ct", op: "delete",
    label: "Bengaluru Urban · duplicate Anekal Police Station (Town Hall Road, Anekal - 562106)",
    why: "The same station is listed twice (two seed batches with different made-up numbers). The twin row is kept and gets the official number; this one goes.",
    source: "internal duplicate — same name and PIN code in PoliceStation", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6pu4005lmuxn9c7xwcz2", op: "delete",
    label: "Bengaluru Urban · duplicate BTM Layout Police Station (100 Feet Road, BTM Layout - 560076)",
    why: "The same station is listed twice (two seed batches with different made-up numbers). The twin row is kept and gets the official number; this one goes.",
    source: "internal duplicate — same name and PIN code in PoliceStation", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6pu4005gmuxn56dtfm94", op: "delete",
    label: "Bengaluru Urban · duplicate Devanahalli Police Station (NH-44, Devanahalli, Bengaluru - 562110)",
    why: "The same station is listed twice (two seed batches with different made-up numbers). The twin row is kept and gets the official number; this one goes.",
    source: "internal duplicate — same name and PIN code in PoliceStation", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6pu4005mmuxnkzjrwcr2", op: "delete",
    label: "Bengaluru Urban · duplicate Electronic City Police Station (Phase 1, Electronic City - 560100)",
    why: "The same station is listed twice (two seed batches with different made-up numbers). The twin row is kept and gets the official number; this one goes.",
    source: "internal duplicate — same name and PIN code in PoliceStation", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6pu4005hmuxn4dtqgasd", op: "delete",
    label: "Bengaluru Urban · duplicate Hebbal Police Station (Hebbal Outer Ring Road, Bengaluru - 560024)",
    why: "The same station is listed twice (two seed batches with different made-up numbers). The twin row is kept and gets the official number; this one goes.",
    source: "internal duplicate — same name and PIN code in PoliceStation", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6pu4005qmuxnj2kj0jle", op: "delete",
    label: "Bengaluru Urban · duplicate Indiranagar Police Station (100 Feet Road, Indiranagar - 560038)",
    why: "The same station is listed twice (two seed batches with different made-up numbers). The twin row is kept and gets the official number; this one goes.",
    source: "internal duplicate — same name and PIN code in PoliceStation", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6pu4005kmuxnpe8hdrzb", op: "delete",
    label: "Bengaluru Urban · duplicate Jayanagar Police Station (40th Cross, Jayanagar - 560041)",
    why: "The same station is listed twice (two seed batches with different made-up numbers). The twin row is kept and gets the official number; this one goes.",
    source: "internal duplicate — same name and PIN code in PoliceStation", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6pu4005pmuxnmzwa48ed", op: "delete",
    label: "Bengaluru Urban · duplicate K R Puram Police Station (Tin Factory, KR Puram - 560036)",
    why: "The same station is listed twice (two seed batches with different made-up numbers). The twin row is kept and gets the official number; this one goes.",
    source: "internal duplicate — same name and PIN code in PoliceStation", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6pu4005omuxn4n7cw9sg", op: "delete",
    label: "Bengaluru Urban · duplicate Marathahalli Police Station (Outer Ring Road, Marathahalli - 560037)",
    why: "The same station is listed twice (two seed batches with different made-up numbers). The twin row is kept and gets the official number; this one goes.",
    source: "internal duplicate — same name and PIN code in PoliceStation", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6pu4005tmuxn6qxi0hsj", op: "delete",
    label: "Bengaluru Urban · duplicate Sarjapur Police Station (Sarjapur Road, Sarjapur - 562125)",
    why: "The same station is listed twice (two seed batches with different made-up numbers). The twin row is kept and gets the official number; this one goes.",
    source: "internal duplicate — same name and PIN code in PoliceStation", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6pu4005nmuxnv91umhmr", op: "delete",
    label: "Bengaluru Urban · duplicate Whitefield Police Station (ITPB Road, Whitefield - 560066)",
    why: "The same station is listed twice (two seed batches with different made-up numbers). The twin row is kept and gets the official number; this one goes.",
    source: "internal duplicate — same name and PIN code in PoliceStation", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6pu4005fmuxn29zvk9pn", op: "delete",
    label: "Bengaluru Urban · duplicate Yelahanka Police Station (Yelahanka New Town, Bengaluru - 560064)",
    why: "The same station is listed twice (two seed batches with different made-up numbers). The twin row is kept and gets the official number; this one goes.",
    source: "internal duplicate — same name and PIN code in PoliceStation", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00c1muxn2iaemnxl", op: "update",
    label: "Bengaluru Urban · Adugodi Police Station",
    set: { phone: "080-22942573", email: "adugodibcp@ksp.gov.in" },
    was: { phone: "080-25542100", email: null },
    why: "Invented number 080-25542100 (seed pattern …100/…400). The KSP statewide directory lists PI Adugodi PS as 22942573.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI Adugodi PS | 22942573 | adugodibcp@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00c5muxn0v0x3qku", op: "update",
    label: "Bengaluru Urban · Anekal Police Station",
    set: { phone: "080-27859235", email: "anekalbng@ksp.gov.in" },
    was: { phone: "080-27822100", email: null },
    why: "Invented number 080-27822100 (seed pattern …100/…400). The KSP statewide directory lists PI Anekal PS as 27859235.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI Anekal PS | 27859235 | anekalbng@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00aymuxnajr2jg1h", op: "update",
    label: "Bengaluru Urban · Ashok Nagar Police Station",
    set: { phone: "080-22942580", email: "anagarbcp@ksp.gov.in" },
    was: { phone: "080-22250585", email: null },
    why: "Invented number 080-22250585 (seed pattern …100/…400). The KSP statewide directory lists PI Ashoknagar PS as 22942580.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI Ashoknagar PS | 22942580 22942076 | anagarbcp@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00c8muxn7y4ma7f7", op: "update",
    label: "Bengaluru Urban · Attibele Police Station",
    set: { phone: "080-27821360", email: "attibelebng@ksp.gov.in" },
    was: { phone: "080-27831100", email: null },
    why: "Invented number 080-27831100 (seed pattern …100/…400). The KSP statewide directory lists PI Attibele PS as 27821360.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI Attibele PS | 27821360 | attibelebng@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00c0muxnboogtgty", op: "delete",
    label: "Bengaluru Urban · BTM Layout Police Station (BTM Layout 1st Stage, Bengaluru 560029)",
    why: "Hidden: unverifiable. No 'BTM Layout Police Station' in the Karnataka State Police directory (Bengaluru City and Bengaluru District lists); the row and its number 080-26780100 look invented.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00bemuxnwmvgfmxl", op: "update",
    label: "Bengaluru Urban · Bagalgunte Police Station",
    set: { phone: "080-22942258", email: "bagalguntepsbcp@ksp.gov.in" },
    was: { phone: "080-28492100", email: null },
    why: "Invented number 080-28492100 (seed pattern …100/…400). The KSP statewide directory lists PI Bagalgunte PS as 22942258.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI Bagalgunte PS | 22942258 | bagalguntepsbcp@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00bjmuxn62rvo5nu", op: "update",
    label: "Bengaluru Urban · Banashankari Police Station",
    set: { phone: "080-22942564", email: "bskbcpbcp@ksp.gov.in" },
    was: { phone: "080-26723100", email: null },
    why: "Invented number 080-26723100 (seed pattern …100/…400). The KSP statewide directory lists PI Banashankari PS as 22942564.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI Banashankari PS | 22942564 26710245 | bskbcpbcp@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00bqmuxnwk3xs5fl", op: "update",
    label: "Bengaluru Urban · Banaswadi Police Station",
    set: { phone: "080-22942552", email: "bwadibcp@ksp.gov.in" },
    was: { phone: "080-25470100", email: null },
    why: "Invented number 080-25470100 (seed pattern …100/…400). The KSP statewide directory lists PI Banaswadi PS as 22942552.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI Banaswadi PS | 22942552 | bwadibcp@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00camuxnd2h6qqki", op: "delete",
    label: "Bengaluru Urban · Bannerghatta Road Police Station (Bannerghatta Road, Bengaluru 560083)",
    why: "Hidden: unverifiable. No 'Bannerghatta Road Police Station' in the Karnataka State Police directory (Bengaluru City and Bengaluru District lists); the row and its number 080-26485100 look invented.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6pu4005jmuxn8xzdijvt", op: "update",
    label: "Bengaluru Urban · Basavanagudi Police Station",
    set: { phone: "080-22942057", email: "bgudibcp@ksp.gov.in" },
    was: { phone: "080-26603400", email: null },
    why: "Invented number 080-26603400 (seed pattern …100/…400). The KSP statewide directory lists PI Basavanagudi PS as 22942057.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI Basavanagudi PS | 22942057 | bgudibcp@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00c9muxnsnlym6x2", op: "update",
    label: "Bengaluru Urban · Begur Police Station",
    set: { phone: "080-22942551", email: "begurbcp@ksp.gov.in" },
    was: { phone: "080-28441100", email: null },
    why: "Invented number 080-28441100 (seed pattern …100/…400). The KSP statewide directory lists PI Beguru PS as 22942551.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI Beguru PS | 22942551 | begurbcp@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00bxmuxny4l3ssbf", op: "update",
    label: "Bengaluru Urban · Bellandur Police Station",
    set: { phone: "080-25747771", email: "bellandurubcp@ksp.gov.in" },
    was: { phone: "080-28442100", email: null },
    why: "Invented number 080-28442100 (seed pattern …100/…400). The KSP statewide directory lists PI Bellanduru PS as 25747771.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI Bellanduru PS | 25747771 | bellandurubcp@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00bamuxnewnmcbmt", op: "update",
    label: "Bengaluru Urban · Byatarayanapura Police Station",
    set: { phone: "080-22942507", email: "bypurabcp@ksp.gov.in" },
    was: { phone: "080-28495100", email: null },
    why: "Invented number 080-28495100 (seed pattern …100/…400). The KSP statewide directory lists PI Byatarayanapura PS as 22942507.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI Byatarayanapura PS | 22942507 | bypurabcp@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00c7muxnmlae3oyy", op: "delete",
    label: "Bengaluru Urban · Chandapura Police Station (Chandapura, Bengaluru 562106)",
    why: "Hidden: unverifiable. No 'Chandapura Police Station' in the Karnataka State Police directory (Bengaluru City and Bengaluru District lists); the row and its number 080-27845100 look invented.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00bpmuxn6zlnxsdp", op: "delete",
    label: "Bengaluru Urban · Chickpet Police Station (Chickpet, Bengaluru 560053)",
    why: "Hidden: unverifiable. No 'Chickpet Police Station' in the Karnataka State Police directory (Bengaluru City and Bengaluru District lists); the row and its number 080-22875100 look invented.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00bomuxnm8fi1jpr", op: "update",
    label: "Bengaluru Urban · Cottonpet Police Station",
    set: { phone: "080-22942508", email: "cotpetbcp@ksp.gov.in" },
    was: { phone: "080-22874100", email: null },
    why: "Invented number 080-22874100 (seed pattern …100/…400). The KSP statewide directory lists PI Cottonpete PS as 22942508.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI Cottonpete PS | 22942508 26700675 | cotpetbcp@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00axmuxnqwgfxnrn", op: "update",
    label: "Bengaluru Urban · Cubbon Park Police Station",
    set: { phone: "080-22942591", email: "cparkbcp@ksp.gov.in" },
    was: { phone: "080-22942222", email: null },
    why: "Invented number 080-22942222 (seed pattern …100/…400). The KSP statewide directory lists PI Cubbon Park PS as 22942591.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI Cubbon Park PS | 22942591 22942087 | cparkbcp@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00b7muxnt5qfwvsz", op: "update",
    label: "Bengaluru Urban · Devanahalli Police Station",
    set: { phone: "080-27680333", email: "devanahallipsbcp@ksp.gov.in" },
    was: { phone: "080-27683100", email: null },
    why: "Invented number 080-27683100 (seed pattern …100/…400). The KSP statewide directory lists PI Devanahalli PS as 27680333.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI Devanahalli PS | 27680333 | devanahallipsbcp@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00bdmuxntc3exgyo", op: "delete",
    label: "Bengaluru Urban · Doddaballapur Police Station (Doddaballapur Town, Bengaluru Rural 561203)",
    why: "Hidden: Doddaballapur is in Bengaluru Rural district (Doddaballapura Town PS belongs to the Bengaluru District Police), not Bengaluru Urban; its phone 08033-265100 was invented.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6pu4005smuxn4cp9wwp8", op: "delete",
    label: "Bengaluru Urban · Electronic City Phase II Police Station (Phase 2, Electronic City - 560100)",
    why: "Hidden: unverifiable. No 'Electronic City Phase II Police Station' in the Karnataka State Police directory (Bengaluru City and Bengaluru District lists); the row and its number 080-28521400 look invented.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00c4muxnp1owd5mv", op: "update",
    label: "Bengaluru Urban · Electronic City Police Station",
    set: { phone: "080-22943469", email: "electroniccitybcp@ksp.gov.in" },
    was: { phone: "080-28520100", email: null },
    why: "Invented number 080-28520100 (seed pattern …100/…400). The KSP statewide directory lists PI Electronic City PS as 22943469.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI Electronic City PS | 22943469 22943476 | electroniccitybcp@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00bsmuxnrq498u4q", op: "update",
    label: "Bengaluru Urban · HAL Police Station",
    set: { phone: "080-22942542", email: "halbcp@ksp.gov.in" },
    was: { phone: "080-25221100", email: null },
    why: "Invented number 080-25221100 (seed pattern …100/…400). The KSP statewide directory lists PI H.A.L PS as 22942542.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI H.A.L PS | 22942542 | halbcp@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00bymuxnknyh87mx", op: "update",
    label: "Bengaluru Urban · HSR Layout Police Station",
    set: { phone: "080-22943467", email: "hsrlayoutbcp@ksp.gov.in" },
    was: { phone: "080-22943100", email: null },
    why: "Invented number 080-22943100 (seed pattern …100/…400). The KSP statewide directory lists PI H.S.R Layout PS as 22943467.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI H.S.R Layout PS | 22943467 | hsrlayoutbcp@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00b8muxnhw02hn1m", op: "update",
    label: "Bengaluru Urban · Hebbal Police Station",
    set: { phone: "080-22942535", email: "hebbalbcp@ksp.gov.in" },
    was: { phone: "080-23630100", email: null },
    why: "Invented number 080-23630100 (seed pattern …100/…400). The KSP statewide directory lists PI Hebbala PS as 22942535.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI Hebbala PS | 22942535 | hebbalbcp@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00bcmuxnkzjerorm", op: "delete",
    label: "Bengaluru Urban · Hesaraghatta Police Station (Hesaraghatta Road, Bengaluru 560088)",
    why: "Hidden: unverifiable. No 'Hesaraghatta Police Station' in the Karnataka State Police directory (Bengaluru City and Bengaluru District lists); the row and its number 080-28482100 look invented.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00azmuxnzhl7ydm3", op: "update",
    label: "Bengaluru Urban · High Grounds Police Station",
    set: { phone: "080-22942587", email: "hgroundbcp@ksp.gov.in" },
    was: { phone: "080-22252777", email: null },
    why: "Invented number 080-22252777 (seed pattern …100/…400). The KSP statewide directory lists PI High Ground PS as 22942587.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI High Ground PS | 22942587 22942083 | hgroundbcp@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00brmuxn6qkup40o", op: "update",
    label: "Bengaluru Urban · Indiranagar Police Station",
    set: { phone: "080-22942541", email: "inagarbcp@ksp.gov.in" },
    was: { phone: "080-25276100", email: null },
    why: "Invented number 080-25276100 (seed pattern …100/…400). The KSP statewide directory lists PI Indiranagar PS as 22942541.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI Indiranagar PS | 22942541 | inagarbcp@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00bimuxnrmod4ybj", op: "update",
    label: "Bengaluru Urban · JP Nagar Police Station",
    set: { phone: "080-22942563", email: "jpnagarbcp@ksp.gov.in" },
    was: { phone: "080-26595100", email: null },
    why: "Invented number 080-26595100 (seed pattern …100/…400). The KSP statewide directory lists PI J.P. Nagar PS as 22942563.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI J.P. Nagar PS | 22942563 | jpnagarbcp@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00b5muxnqmh7dfuu", op: "update",
    label: "Bengaluru Urban · Jalahalli Police Station",
    set: { phone: "080-22942527", email: "jhallibcp@ksp.gov.in" },
    was: { phone: "080-28395100", email: null },
    why: "Invented number 080-28395100 (seed pattern …100/…400). The KSP statewide directory lists PI Jalahalli PS as 22942527.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI Jalahalli PS | 22942527 | jhallibcp@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00bhmuxnq7blj5cu", op: "update",
    label: "Bengaluru Urban · Jayanagar Police Station",
    set: { phone: "080-22942562", email: "pijnagarbcp@ksp.gov.in" },
    was: { phone: "080-26634100", email: null },
    why: "Invented number 080-26634100 (seed pattern …100/…400). The KSP statewide directory lists PI Jayanagar PS as 22942562.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI Jayanagar PS | 22942562 | pijnagarbcp@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00bvmuxnb3j4uz4r", op: "update",
    label: "Bengaluru Urban · KR Puram Police Station",
    set: { phone: "080-22942553", email: "krpurambcp@ksp.gov.in" },
    was: { phone: "080-25631100", email: null },
    why: "Invented number 080-25631100 (seed pattern …100/…400). The KSP statewide directory lists PI K.R. Puram PS as 22942553.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI K.R. Puram PS | 22942553 | krpurambcp@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00bkmuxndhyw7qyz", op: "delete",
    label: "Bengaluru Urban · Kanakapura Road Police Station (Kanakapura Road, Bengaluru 560062)",
    why: "Hidden: unverifiable. No 'Kanakapura Road Police Station' in the Karnataka State Police directory (Bengaluru City and Bengaluru District lists); the row and its number 080-26484100 look invented.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00bfmuxn0wxnve5p", op: "update",
    label: "Bengaluru Urban · Kodigehalli Police Station",
    set: { phone: "080-22943703", email: "pikodigehallibcp@ksp.gov.in" },
    was: { phone: "080-28485100", email: null },
    why: "Invented number 080-28485100 (seed pattern …100/…400). The KSP statewide directory lists PI Kodigehalli PS as 22943703.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI Kodigehalli PS | 22943703 | pikodigehallibcp@ksp.gov.in kodigehallibcp@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00c2muxnmzf89u3o", op: "update",
    label: "Bengaluru Urban · Koramangala Police Station",
    set: { phone: "080-22942570", email: "kmangalabcp@ksp.gov.in" },
    was: { phone: "080-25527100", email: null },
    why: "Invented number 080-25527100 (seed pattern …100/…400). The KSP statewide directory lists PI Koramangala PS as 22942570.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI Koramangala PS | 22942570 | kmangalabcp@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00bgmuxn43mo8jx2", op: "delete",
    label: "Bengaluru Urban · Lalbagh Police Station (Lalbagh Road, Bengaluru 560027)",
    why: "Hidden: unverifiable. No 'Lalbagh Police Station' in the Karnataka State Police directory (Bengaluru City and Bengaluru District lists); the row and its number 080-26711100 look invented.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00bzmuxnf4awooy8", op: "update",
    label: "Bengaluru Urban · Madivala Police Station",
    set: { phone: "080-22942568", email: "madivalabcp@ksp.gov.in" },
    was: { phone: "080-26742100", email: null },
    why: "Invented number 080-26742100 (seed pattern …100/…400). The KSP statewide directory lists PI Madivala PS as 22942568.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI Madivala PS | 22942568 | madivalabcp@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00bumuxnoc8dnuek", op: "update",
    label: "Bengaluru Urban · Mahadevapura Police Station",
    set: { phone: "080-22942546", email: "mdpurabcp@ksp.gov.in" },
    was: { phone: "080-28448100", email: null },
    why: "Invented number 080-28448100 (seed pattern …100/…400). The KSP statewide directory lists PI Mahadevapura PS as 22942546.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI Mahadevapura PS | 22942546 | mdpurabcp@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00b2muxnuj6bcoyc", op: "update",
    label: "Bengaluru Urban · Malleswaram Police Station",
    set: { phone: "080-22942519", email: "mvmbcp@ksp.gov.in" },
    was: { phone: "080-23315400", email: null },
    why: "Invented number 080-23315400 (seed pattern …100/…400). The KSP statewide directory lists PI Malleshwaram PS as 22942519.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI Malleshwaram PS | 22942519 | mvmbcp@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00bwmuxn79gbn9mm", op: "update",
    label: "Bengaluru Urban · Marathahalli Police Station",
    set: { phone: "080-25639999", email: "marathahallibcp@ksp.gov.in" },
    was: { phone: "080-25243100", email: null },
    why: "Invented number 080-25243100 (seed pattern …100/…400). The KSP statewide directory lists PI Marathahalli PS as 25639999.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI Marathahalli PS | 25639999 | marathahallibcp@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00b9muxnerhay3ty", op: "update",
    label: "Bengaluru Urban · RT Nagar Police Station",
    set: { phone: "080-22942538", email: "rtnagarbcp@ksp.gov.in" },
    was: { phone: "080-23332100", email: null },
    why: "Invented number 080-23332100 (seed pattern …100/…400). The KSP statewide directory lists PI R.T. Nagar PS as 22942538.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI R.T. Nagar PS | 22942538 | rtnagarbcp@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00b3muxnylq5hby1", op: "update",
    label: "Bengaluru Urban · Rajajinagar Police Station",
    set: { phone: "080-22942522", email: "rnagarbcp@ksp.gov.in" },
    was: { phone: "080-23154100", email: null },
    why: "Invented number 080-23154100 (seed pattern …100/…400). The KSP statewide directory lists PI Rajajinagar PS as 22942522.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI Rajajinagar PS | 22942522 | rnagarbcp@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6pu4005imuxn52nwntwy", op: "update",
    label: "Bengaluru Urban · Sadashivanagar Police Station",
    set: { phone: "080-22942589", email: "ssnagarabcp@ksp.gov.in" },
    was: { phone: "080-23606400", email: null },
    why: "Invented number 080-23606400 (seed pattern …100/…400). The KSP statewide directory lists PI Sadashiva Nagar PS as 22942589.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI Sadashiva Nagar PS | 22942589 22942085 | ssnagarabcp@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00c6muxnvo5r1wjp", op: "update",
    label: "Bengaluru Urban · Sarjapur Police Station",
    set: { phone: "080-27823032", email: "sarjapurabng@ksp.gov.in" },
    was: { phone: "080-28438100", email: null },
    why: "Invented number 080-28438100 (seed pattern …100/…400). The KSP statewide directory lists PI Sarjapura PS as 27823032.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI Sarjapura PS | 27823032 | sarjapurabng@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00b1muxnu7hf5y2q", op: "update",
    label: "Bengaluru Urban · Seshadripuram Police Station",
    set: { phone: "080-22942586", email: "sspurambcp@ksp.gov.in" },
    was: { phone: "080-23461100", email: null },
    why: "Invented number 080-23461100 (seed pattern …100/…400). The KSP statewide directory lists PI Seshadripuram PS as 22942586.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI Seshadripuram PS | 22942586 22942082 | sspurambcp@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00b0muxn61u87zaf", op: "update",
    label: "Bengaluru Urban · Shivajinagar Police Station",
    set: { phone: "080-22942597", email: "snagarbcp@ksp.gov.in" },
    was: { phone: "080-25550100", email: null },
    why: "Invented number 080-25550100 (seed pattern …100/…400). The KSP statewide directory lists PI Shivajinagar PS as 22942597.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI Shivajinagar PS | 22942597 | snagarbcp@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00bmmuxny9y0xvmx", op: "update",
    label: "Bengaluru Urban · Srirampuram Police Station",
    set: { phone: "080-22942520", email: "srpurambcp@ksp.gov.in" },
    was: { phone: "080-23490100", email: null },
    why: "Invented number 080-23490100 (seed pattern …100/…400). The KSP statewide directory lists PI Srirampura PS as 22942520.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI Srirampura PS | 22942520 | srpurambcp@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00bnmuxncs89bhsk", op: "update",
    label: "Bengaluru Urban · Subramanyanagar Police Station",
    set: { phone: "080-22942524", email: "sbnagarbcp@ksp.gov.in" },
    was: { phone: "080-23305100", email: null },
    why: "Invented number 080-23305100 (seed pattern …100/…400). The KSP statewide directory lists PI Subramanya Nagar PS as 22942524.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI Subramanya Nagar PS | 22942524 | sbnagarbcp@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00bbmuxn7yx7jnjy", op: "update",
    label: "Bengaluru Urban · Vidyaranyapura Police Station",
    set: { phone: "080-22942528", email: "vrpurabcp@ksp.gov.in" },
    was: { phone: "080-28483100", email: null },
    why: "Invented number 080-28483100 (seed pattern …100/…400). The KSP statewide directory lists PI Vidyaranyapura PS as 22942528.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI Vidyaranyapura PS | 22942528 | vrpurabcp@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00blmuxnlazdrc24", op: "update",
    label: "Bengaluru Urban · Vijayanagar Police Station",
    set: { phone: "080-22942514", email: "vjnagarbcp@ksp.gov.in" },
    was: { phone: "080-23307100", email: null },
    why: "Invented number 080-23307100 (seed pattern …100/…400). The KSP statewide directory lists PI Vijayanagar PS as 22942514.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI Vijayanagar PS | 22942514 | vjnagarbcp@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00btmuxno0uflerp", op: "update",
    label: "Bengaluru Urban · Whitefield Police Station",
    set: { phone: "080-22943472", email: "whitefieldbcp@ksp.gov.in" },
    was: { phone: "080-28450100", email: null },
    why: "Invented number 080-28450100 (seed pattern …100/…400). The KSP statewide directory lists PI Whitefield PS as 22943472.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI Whitefield PS | 22943472 | whitefieldbcp@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00c3muxnzogcl9yc", op: "update",
    label: "Bengaluru Urban · Wilson Garden Police Station",
    set: { phone: "080-22942581", email: "wgardenbcp@ksp.gov.in" },
    was: { phone: "080-22272100", email: null },
    why: "Invented number 080-22272100 (seed pattern …100/…400). The KSP statewide directory lists PI Wilson Garden PS as 22942581.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI Wilson Garden PS | 22942581 22942077 | wgardenbcp@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00b6muxn3pktdcvz", op: "update",
    label: "Bengaluru Urban · Yelahanka Police Station",
    set: { phone: "080-22942536", email: "ylankabcp@ksp.gov.in" },
    was: { phone: "080-28461100", email: null },
    why: "Invented number 080-28461100 (seed pattern …100/…400). The KSP statewide directory lists PI Yelahanka PS as 22942536.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI Yelahanka PS | 22942536 | ylankabcp@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmmvn6tws00b4muxn0spkezu1", op: "update",
    label: "Bengaluru Urban · Yeshwanthpur Police Station",
    set: { phone: "080-22942526", email: "yspurabcp@ksp.gov.in" },
    was: { phone: "080-23375100", email: null },
    why: "Invented number 080-23375100 (seed pattern …100/…400). The KSP statewide directory lists PI Yeshwanthapura PS as 22942526.",
    source: "https://ksp.karnataka.gov.in/ksp_contact/en", says: "PI Yeshwanthapura PS | 22942526 | yspurabcp@ksp.gov.in", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3rud001w51xng0fgxaql", op: "update",
    label: "Chennai · Adyar Police Station",
    set: { phone: null },
    was: { phone: "044-24910013" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3rud002651xnqsfi7e8t", op: "update",
    label: "Chennai · Ambattur Police Station",
    set: { phone: null },
    was: { phone: "044-26530100" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3rud001x51xnclv61p9o", op: "update",
    label: "Chennai · Anna Nagar Police Station",
    set: { phone: null },
    was: { phone: "044-26261100" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3rud002b51xnzct26ezu", op: "update",
    label: "Chennai · Broadway Police Station",
    set: { phone: null },
    was: { phone: "044-25340100" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3rud001y51xnq7ooc56u", op: "update",
    label: "Chennai · Egmore Police Station",
    set: { phone: null },
    was: { phone: "044-28190100" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3rud001z51xnsrq1zam7", op: "update",
    label: "Chennai · Guindy Police Station",
    set: { phone: null },
    was: { phone: "044-22350545" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3rud002251xnm42ggij0", op: "update",
    label: "Chennai · Kilpauk Police Station",
    set: { phone: null },
    was: { phone: "044-26411221" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3rud002d51xns03ordbl", op: "update",
    label: "Chennai · Kodambakkam Police Station",
    set: { phone: null },
    was: { phone: "044-24830100" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3rud002751xnzputf95h", op: "update",
    label: "Chennai · Madhavaram Police Station",
    set: { phone: null },
    was: { phone: "044-25550100" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3ruc001u51xn6ds6dekl", op: "update",
    label: "Chennai · Mylapore Police Station",
    set: { phone: null },
    was: { phone: "044-24641212" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3rud002051xnaowoexvj", op: "update",
    label: "Chennai · Nungambakkam Police Station",
    set: { phone: null },
    was: { phone: "044-28270221" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3rud002a51xn0hvo1w1d", op: "update",
    label: "Chennai · Perambur Police Station",
    set: { phone: null },
    was: { phone: "044-25511221" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3rud002851xn6rrn7upl", op: "update",
    label: "Chennai · Porur Police Station",
    set: { phone: null },
    was: { phone: "044-24760100" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3rud002151xnnktckn4p", op: "update",
    label: "Chennai · Royapettah Police Station",
    set: { phone: null },
    was: { phone: "044-28110100" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3rud002951xnw2me2gsw", op: "update",
    label: "Chennai · Sholinganallur Police Station",
    set: { phone: null },
    was: { phone: "044-24501100" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3rud001v51xnlew7tsp8", op: "update",
    label: "Chennai · T Nagar Police Station",
    set: { phone: null },
    was: { phone: "044-24340750" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3rud002451xnz8570xsg", op: "update",
    label: "Chennai · Tambaram Police Station",
    set: { phone: null },
    was: { phone: "044-22260550" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3rud002c51xn9e1pgbbb", op: "update",
    label: "Chennai · Thiruvanmiyur Police Station",
    set: { phone: null },
    was: { phone: "044-24424100" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3rud002351xn7jlyixjf", op: "update",
    label: "Chennai · Tondiarpet Police Station",
    set: { phone: null },
    was: { phone: "044-25951100" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3rud002551xn5jucympd", op: "update",
    label: "Chennai · Velachery Police Station",
    set: { phone: null },
    was: { phone: "044-22590523" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnrsych30018yaxnsd54suvy", op: "update",
    label: "Hyderabad · Abids PS",
    set: { phone: null },
    was: { phone: "040-27854814" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnrsych30019yaxn5gdfemz9", op: "update",
    label: "Hyderabad · Afzalgunj PS",
    set: { phone: null },
    was: { phone: "040-24515293" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnrsych4001iyaxnns1k69r4", op: "update",
    label: "Hyderabad · Bahadurpura PS",
    set: { phone: null },
    was: { phone: "040-24515250" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnrsych3001ayaxn3ioi7k9z", op: "update",
    label: "Hyderabad · Charminar PS",
    set: { phone: null },
    was: { phone: "040-24515888" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnrsych3001byaxnxh85vjva", op: "update",
    label: "Hyderabad · Falaknuma PS",
    set: { phone: null },
    was: { phone: "040-24515155" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnrsych4001hyaxnkg45r3cm", op: "update",
    label: "Hyderabad · Golconda PS",
    set: { phone: null },
    was: { phone: "040-23521000" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnrsych4001myaxn2cxyi4gd", op: "update",
    label: "Hyderabad · Habeebnagar PS",
    set: { phone: null },
    was: { phone: "040-23223625" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnrsych4001cyaxndz6y7dd8", op: "update",
    label: "Hyderabad · Hussainialam PS",
    set: { phone: null },
    was: { phone: "040-24515533" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnrsych4001dyaxn6dfwhtxs", op: "update",
    label: "Hyderabad · Kacheguda PS",
    set: { phone: null },
    was: { phone: "040-27854133" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnrsych4001kyaxnnz48f7ya", op: "update",
    label: "Hyderabad · Malakpet PS",
    set: { phone: null },
    was: { phone: "040-24061100" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnrsych4001lyaxngckdkrrg", op: "update",
    label: "Hyderabad · Mangalhat PS",
    set: { phone: null },
    was: { phone: "040-23220678" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnrsych4001eyaxnjzplnb2h", op: "update",
    label: "Hyderabad · Musheerabad PS",
    set: { phone: null },
    was: { phone: "040-27853855" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnrsych30017yaxnjmw9g8qu", op: "update",
    label: "Hyderabad · Nampally PS",
    set: { phone: null },
    was: { phone: "040-27853252" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnrsych4001fyaxnqbuvgylk", op: "update",
    label: "Hyderabad · Narayanguda PS",
    set: { phone: null },
    was: { phone: "040-27854920" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnrsych4001jyaxnnm2qgne0", op: "update",
    label: "Hyderabad · Saidabad PS",
    set: { phone: null },
    was: { phone: "040-24061050" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnrsych4001gyaxn30vm0v0q", op: "update",
    label: "Hyderabad · Sultan Bazaar PS",
    set: { phone: null },
    was: { phone: "040-27854050" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3nyp001x4exn3gdrmgsz", op: "update",
    label: "Kolkata · Alipore Police Station",
    set: { phone: null },
    was: { phone: "033-24795050" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3nyp00234exn7qpdmauw", op: "update",
    label: "Kolkata · Beliaghata Police Station",
    set: { phone: null },
    was: { phone: "033-23501100" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3nyp001t4exniqnoyhma", op: "update",
    label: "Kolkata · Bhawanipur Police Station",
    set: { phone: null },
    was: { phone: "033-24741225" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3nyp001r4exncqzzalnd", op: "update",
    label: "Kolkata · Bowbazar Police Station",
    set: { phone: null },
    was: { phone: "033-22366200" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3nyp00254exnmoa4bekm", op: "update",
    label: "Kolkata · Cossipore Police Station",
    set: { phone: null },
    was: { phone: "033-25563500" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3nyp00264exnwg1v7cja", op: "update",
    label: "Kolkata · Entally Police Station",
    set: { phone: null },
    was: { phone: "033-22842000" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3nyp00214exndkst5ig5", op: "update",
    label: "Kolkata · Garden Reach Police Station",
    set: { phone: null },
    was: { phone: "033-24690250" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3nyp001v4exnahq6nx6g", op: "update",
    label: "Kolkata · Gariahat Police Station",
    set: { phone: null },
    was: { phone: "033-24610320" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3nyp00244exnzt5qgchp", op: "update",
    label: "Kolkata · Hare Street Police Station",
    set: { phone: null },
    was: { phone: "033-22481200" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3nyp001z4exn92647i15", op: "update",
    label: "Kolkata · Jadavpur Police Station",
    set: { phone: null },
    was: { phone: "033-24732000" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3nyp001s4exn4fnqrn8q", op: "update",
    label: "Kolkata · Jorasanko Police Station",
    set: { phone: null },
    was: { phone: "033-22690250" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3nyp00274exnilck6fv7", op: "update",
    label: "Kolkata · Kasba Police Station",
    set: { phone: null },
    was: { phone: "033-24420250" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3nyp00224exn4jt3w04p", op: "update",
    label: "Kolkata · Kidderpore Police Station",
    set: { phone: null },
    was: { phone: "033-24494350" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3nyp001u4exnwrhwgk3c", op: "delete",
    label: "Kolkata · Lake Town Police Station (VIP Road, Lake Town, Kolkata 700089)",
    why: "Hidden: Lake Town is under the Bidhannagar Police Commissionerate (North 24 Parganas), not Kolkata district; number 033-25285000 unverified.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3nyo001o4exnkzdtmwmo", op: "update",
    label: "Kolkata · Lalbazar (Kolkata Police HQ)",
    set: { phone: null },
    was: { phone: "033-22143024" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3nyp001q4exnt8eja5m2", op: "update",
    label: "Kolkata · New Market Police Station",
    set: { phone: null },
    was: { phone: "033-22521515" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3nyp001p4exnwlevclpz", op: "update",
    label: "Kolkata · Park Street Police Station",
    set: { phone: null },
    was: { phone: "033-22170460" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3nyp00204exn6zy4muln", op: "delete",
    label: "Kolkata · Salt Lake Police Station (Sector V, Salt Lake, Kolkata 700091)",
    why: "Hidden: Salt Lake (Bidhannagar) is in North 24 Parganas under the Bidhannagar Police Commissionerate, not Kolkata district; number 033-23591000 unverified.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3nyp001y4exnah6uqse5", op: "update",
    label: "Kolkata · Shyambazar Police Station",
    set: { phone: null },
    was: { phone: "033-25534350" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3nyp001w4exnpmh9jw3d", op: "update",
    label: "Kolkata · Tollygunge Police Station",
    set: { phone: null },
    was: { phone: "033-24231000" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmntdqtga000ylnxnytmw49oo", op: "update",
    label: "Lucknow · Alambagh PS",
    set: { phone: null },
    was: { phone: "0522-2455100" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmntdqtga000slnxnr1fuq333", op: "update",
    label: "Lucknow · Aliganj PS",
    set: { phone: null },
    was: { phone: "0522-2325400" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmntdqtga000vlnxns6jsys6y", op: "update",
    label: "Lucknow · Ashiana PS",
    set: { phone: null },
    was: { phone: "0522-2422100" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmntdqtga0010lnxncyx1bq3d", op: "update",
    label: "Lucknow · Cantonment PS",
    set: { phone: null },
    was: { phone: "0522-2281200" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmntdqtga000ulnxnkm8i30iw", op: "update",
    label: "Lucknow · Chinhat PS",
    set: { phone: null },
    was: { phone: "0522-2670100" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmntdqtga000plnxnpqulsm7r", op: "update",
    label: "Lucknow · Chowk PS",
    set: { phone: null },
    was: { phone: "0522-2252100" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmntdqtga000rlnxnp7pwqt6x", op: "update",
    label: "Lucknow · Gomti Nagar PS",
    set: { phone: null },
    was: { phone: "0522-2305100" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmntdqtga0012lnxnbqfx66hu", op: "update",
    label: "Lucknow · Gudamba PS",
    set: { phone: null },
    was: { phone: "0522-2282100" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmntdqtga000olnxnfwq3urtl", op: "update",
    label: "Lucknow · Hazratganj PS",
    set: { phone: null },
    was: { phone: "0522-2623399" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmntdqtga000tlnxnypilrjzl", op: "update",
    label: "Lucknow · Indira Nagar PS",
    set: { phone: null },
    was: { phone: "0522-2354100" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmntdqtga0011lnxn1wpi7q94", op: "update",
    label: "Lucknow · Jankipuram PS",
    set: { phone: null },
    was: { phone: "0522-2730100" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmntdqtga000qlnxnkgnl3y4x", op: "update",
    label: "Lucknow · Kaiserbagh PS",
    set: { phone: null },
    was: { phone: "0522-2622400" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmntdqtga000xlnxnmo0jwbpg", op: "update",
    label: "Lucknow · Mahanagar PS",
    set: { phone: null },
    was: { phone: "0522-2386100" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmntdqtga000zlnxn354xlrar", op: "update",
    label: "Lucknow · Sarojini Nagar PS",
    set: { phone: null },
    was: { phone: "0522-2415200" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmntdqtga000wlnxn88v3i0rg", op: "update",
    label: "Lucknow · Vibhuti Khand PS",
    set: { phone: null },
    was: { phone: "0522-2301600" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3g48002b3rxnnpatr4mp", op: "update",
    label: "Mumbai · Andheri Police Station",
    set: { phone: null },
    was: { phone: "022-26281515" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3g4800273rxnxr7dya7x", op: "update",
    label: "Mumbai · Azad Maidan Police Station",
    set: { phone: null },
    was: { phone: "022-22620974" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3g4800293rxnv2no4ksn", op: "update",
    label: "Mumbai · Bandra Police Station",
    set: { phone: null },
    was: { phone: "022-26420245" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3g48002c3rxn2c83j5ap", op: "update",
    label: "Mumbai · Borivali Police Station",
    set: { phone: null },
    was: { phone: "022-28933510" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3g4800253rxn0ootnee7", op: "update",
    label: "Mumbai · Colaba Police Station",
    set: { phone: null },
    was: { phone: "022-22161613" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3g4800283rxnqyp0jigs", op: "update",
    label: "Mumbai · DN Nagar Police Station",
    set: { phone: null },
    was: { phone: "022-26283251" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3g48002e3rxnp3ccp2ro", op: "update",
    label: "Mumbai · Dadar Police Station",
    set: { phone: null },
    was: { phone: "022-24229502" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3g48002k3rxnr22qlw6y", op: "update",
    label: "Mumbai · Dharavi Police Station",
    set: { phone: null },
    was: { phone: "022-24044888" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3g48002g3rxnpcybasrv", op: "update",
    label: "Mumbai · Ghatkopar Police Station",
    set: { phone: null },
    was: { phone: "022-25002210" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3g48002i3rxnikrpg43j", op: "update",
    label: "Mumbai · Goregaon Police Station",
    set: { phone: null },
    was: { phone: "022-28721777" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3g48002a3rxn9469tprq", op: "update",
    label: "Mumbai · Juhu Police Station",
    set: { phone: null },
    was: { phone: "022-26362929" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3g48002l3rxn4wprfif4", op: "update",
    label: "Mumbai · Kandivali Police Station",
    set: { phone: null },
    was: { phone: "022-28052055" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3g48002f3rxnp6vcrjjg", op: "update",
    label: "Mumbai · Kurla Police Station",
    set: { phone: null },
    was: { phone: "022-26521240" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3g48002d3rxnsly5yzl1", op: "update",
    label: "Mumbai · Malad Police Station",
    set: { phone: null },
    was: { phone: "022-28811002" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3g4800263rxnsr45qop0", op: "update",
    label: "Mumbai · Marine Drive Police Station",
    set: { phone: null },
    was: { phone: "022-22812366" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3g48002h3rxn2w1z0bun", op: "update",
    label: "Mumbai · Powai Police Station",
    set: { phone: null },
    was: { phone: "022-25709264" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3g48002o3rxnvmjfj6ao", op: "update",
    label: "Mumbai · Santacruz Police Station",
    set: { phone: null },
    was: { phone: "022-26490092" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3g48002n3rxnrh0je4mt", op: "update",
    label: "Mumbai · Versova Police Station",
    set: { phone: null },
    was: { phone: "022-26320346" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3g48002m3rxn7r9u00hy", op: "update",
    label: "Mumbai · Vikhroli Police Station",
    set: { phone: null },
    was: { phone: "022-25787070" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnfm3g48002j3rxnh8clan9k", op: "update",
    label: "Mumbai · Worli Police Station",
    set: { phone: null },
    was: { phone: "022-24938571" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnf0n5is001t1dxno25vowf8", op: "update",
    label: "New Delhi · Barakhamba Road Police Station",
    set: { phone: null },
    was: { phone: "011-23313400" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnf0n5is001r1dxnnoiiq30p", op: "update",
    label: "New Delhi · Chanakya Puri Police Station",
    set: { phone: null },
    was: { phone: "011-26114800" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnf0n5is001q1dxn7zykbta2", op: "update",
    label: "New Delhi · Connaught Place Police Station",
    set: { phone: null },
    was: { phone: "011-23362800" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnf0n5is001u1dxnlzpe59qo", op: "update",
    label: "New Delhi · Mandir Marg Police Station",
    set: { phone: null },
    was: { phone: "011-23365400" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnf0n5is001o1dxn684sgzmt", op: "update",
    label: "New Delhi · Parliament Street Police Station",
    set: { phone: null },
    was: { phone: "011-23361000" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnf0n5is001p1dxn8wlorp9a", op: "update",
    label: "New Delhi · Tilak Marg Police Station",
    set: { phone: null },
    was: { phone: "011-23381476" },
    why: "Hidden: unverifiable. Seed number with no source; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
  {
    table: "PoliceStation", id: "cmnf0n5is001s1dxn9obtu89p", op: "update",
    label: "New Delhi · Tughlak Road Police Station",
    set: { phone: null },
    was: { phone: "011-23792600" },
    why: "Hidden: unverifiable. Round-number ending like the rest of this made-up seed batch; the city police site lists stations only through a script the checker could not read, so the real number could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §5", checked: CHECKED,
  },
];
