/**
 * Scheme fixes (checked 27 Sep 2026). Rule: verified or hidden.
 * Scheme rows were seeded in spring 2026 without sources. Amounts that are
 * outdated or wrong-looking, and every unsourced beneficiary count, are
 * cleared; rows for schemes that are wrong for the state or no longer
 * running are deleted. Standard entitlements that match the scheme rules
 * (PM-KISAN Rs 6,000, PM-JAY Rs 5 lakh, Ujjwala Rs 1,600 …) are kept.
 */
import type { Fix } from "./types";

export const SCHEME_FIXES: Fix[] = [
  {
    table: "Scheme", id: "cmmvn6q7o0066muxnakcftuxn", op: "delete",
    label: "Bengaluru Urban · Smart Cities Mission",
    why: "Hidden: unverifiable — the Smart Cities Mission's term ended on 31 Mar 2025; an open-ended 'active' listing is stale.",
    source: "none — see docs/DATA-FIXES-2026-09.md §7", checked: "2026-09-27",
  },
  {
    table: "Scheme", id: "cmnfm3se0003c51xnq21rusai", op: "delete",
    label: "Chennai · TN Free Laptop Scheme",
    why: "Hidden: unverifiable — the Tamil Nadu free-laptop scheme is not known to be running now and could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §7", checked: "2026-09-27",
  },
  {
    table: "Scheme", id: "cmntdqtyj001zlnxnkiq9lx7y", op: "delete",
    label: "Lucknow · Samajwadi Pension Yojana (Old Age/Widow)",
    why: "Hidden: unverifiable — the Samajwadi Pension Yojana is not known to be running now and could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §7", checked: "2026-09-27",
  },
  {
    table: "Scheme", id: "cmntdqtyj001ylnxnmk12daqu", op: "delete",
    label: "Lucknow · UP Berojgari Bhatta (Unemployment Allowance)",
    why: "Hidden: unverifiable — no current UP unemployment-allowance scheme paying Rs 1,500 could be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §7", checked: "2026-09-27",
  },
  {
    table: "Scheme", id: "cmmv9ndcq0052ubxn5f1kx3ih", op: "delete",
    label: "Mandya · Mangala Bhagya",
    why: "Hidden: unverifiable — no Karnataka scheme called 'Mangala Bhagya' paying Rs 3,000 could be found.",
    source: "none — see docs/DATA-FIXES-2026-09.md §7", checked: "2026-09-27",
  },
  {
    table: "Scheme", id: "cmmvn78cw00qsmuxn8gtquck7", op: "delete",
    label: "Mysuru · Aarogyasri Health Insurance",
    why: "Hidden: unverifiable — 'Aarogyasri' is the Telangana/Andhra Pradesh health scheme, not Karnataka's; the 2,18,000 beneficiaries have no source.",
    source: "none — see docs/DATA-FIXES-2026-09.md §7", checked: "2026-09-27",
  },
  {
    table: "Scheme", id: "cmmvn78cw00qtmuxnclkxywo2", op: "delete",
    label: "Mysuru · Mysuru Heritage Tourism Grant",
    why: "Hidden: unverifiable — no 'Mysuru Heritage Tourism Grant' could be found; the Rs 2 lakh amount and 1,200 beneficiaries have no source.",
    source: "none — see docs/DATA-FIXES-2026-09.md §7", checked: "2026-09-27",
  },
  {
    table: "Scheme", id: "cmmvn78cw00qqmuxnjshfm530", op: "delete",
    label: "Mysuru · Mysuru Smart City Scheme",
    why: "Hidden: unverifiable — Mysuru is not one of the 100 Smart Cities; the 9,20,000 beneficiaries have no source.",
    source: "none — see docs/DATA-FIXES-2026-09.md §7", checked: "2026-09-27",
  },
  {
    table: "Scheme", id: "cmmvn6q7o006amuxnmchfvctz", op: "update",
    label: "Bengaluru Urban · Anna Bhagya (Free Rice)",
    set: { amount: null },
    was: { amount: 0 },
    why: "Hidden: unverifiable — Rs 0 is not an entitlement amount (Anna Bhagya gives free rice plus cash in lieu); the current amount was not confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §7", checked: "2026-09-27",
  },
  {
    table: "Scheme", id: "cmmvn6q7o0063muxnfl3t4v2p", op: "update",
    label: "Bengaluru Urban · PMAY-Urban (Housing for All)",
    set: { amount: null },
    was: { amount: 150000 },
    why: "Hidden: unverifiable — PMAY-U amounts changed under PMAY-U 2.0; Rs 1.5 lakh could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §7", checked: "2026-09-27",
  },
  {
    table: "Scheme", id: "cmnf0n6nd002h1dxnfx06uws1", op: "update",
    label: "New Delhi · PMAY-Urban (Housing for All)",
    set: { amount: null },
    was: { amount: 150000 },
    why: "Hidden: unverifiable — PMAY-U amounts changed under PMAY-U 2.0; Rs 1.5 lakh could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §7", checked: "2026-09-27",
  },
  {
    table: "Scheme", id: "cmnfm3se0003f51xnto4u8omn", op: "update",
    label: "Chennai · Pradhan Mantri Awas Yojana — Urban (PMAY-U)",
    set: { amount: null },
    was: { amount: 267000 },
    why: "Hidden: unverifiable — Rs 2.67 lakh was the old CLSS interest subsidy (closed 2022); the current PMAY-U 2.0 amount was not confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §7", checked: "2026-09-27",
  },
  {
    table: "Scheme", id: "cmnfm3gn4003n3rxnjjks6uf9", op: "update",
    label: "Mumbai · Pradhan Mantri Awas Yojana — Urban (PMAY-U)",
    set: { amount: null },
    was: { amount: 267000 },
    why: "Hidden: unverifiable — Rs 2.67 lakh was the old CLSS interest subsidy (closed 2022); the current PMAY-U 2.0 amount was not confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §7", checked: "2026-09-27",
  },
  {
    table: "Scheme", id: "cmobql6qk0000qaxnz30rxvwy", op: "update",
    label: "Pune · Pradhan Mantri Awas Yojana — Urban (PMAY-U)",
    set: { amount: null },
    was: { amount: 267000 },
    why: "Hidden: unverifiable — Rs 2.67 lakh was the old CLSS interest subsidy (closed 2022); the current PMAY-U 2.0 amount was not confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §7", checked: "2026-09-27",
  },
  {
    table: "Scheme", id: "cmmvn6q7o006cmuxndvb0bq5x", op: "update",
    label: "Bengaluru Urban · Rajiv Gandhi Gruha Nirmana Nigama (RGRHCL) — Urban",
    set: { amount: null },
    was: { amount: 150000 },
    why: "Hidden: unverifiable — Rs 1.5 lakh could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §7", checked: "2026-09-27",
  },
  {
    table: "Scheme", id: "cmmv9nd9j0050ubxnqj7xqt1o", op: "update",
    label: "Mandya · Rajiv Gandhi Gruha Nirmana Nigama (RGRHCL)",
    set: { amount: null },
    was: { amount: 150000 },
    why: "Hidden: unverifiable — Rs 1.5 lakh could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §7", checked: "2026-09-27",
  },
  {
    table: "Scheme", id: "cmnrsydox002eyaxnxmvc1szh", op: "update",
    label: "Hyderabad · Aasara Pensions",
    set: { amount: null },
    was: { amount: 24192 },
    why: "Hidden: unverifiable — Rs 24,192 a year (Rs 2,016 a month) may be outdated; the current pension amount was not confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §7", checked: "2026-09-27",
  },
  {
    table: "Scheme", id: "cmnrsydox002fyaxn0nsnd4pj", op: "update",
    label: "Hyderabad · KCR Kit — Maternity Benefit",
    set: { amount: null },
    was: { amount: 12000 },
    why: "Hidden: unverifiable — the scheme's current name and Rs 12,000 amount could not be confirmed after the 2023 change of government.",
    source: "none — see docs/DATA-FIXES-2026-09.md §7", checked: "2026-09-27",
  },
  {
    table: "Scheme", id: "cmntdqtyi001wlnxnzq4mc5m8", op: "update",
    label: "Lucknow · Kanya Sumangala Yojana",
    set: { amount: null },
    was: { amount: 15000 },
    why: "Hidden: unverifiable — Rs 15,000 may be outdated (the amount was reported raised in 2024); not confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §7", checked: "2026-09-27",
  },
  {
    table: "Scheme", id: "cmnfm3gn4003l3rxnzrjnzz6c", op: "update",
    label: "Mumbai · Maharashtra Gharkul Yojana",
    set: { amount: null },
    was: { amount: 250000 },
    why: "Hidden: unverifiable — Rs 2.5 lakh could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §7", checked: "2026-09-27",
  },
  {
    table: "Scheme", id: "cmocx56430002r2xnx5b0k2y4", op: "update",
    label: "Pune · Maharashtra Gharkul Yojana",
    set: { amount: null },
    was: { amount: 250000 },
    why: "Hidden: unverifiable — Rs 2.5 lakh could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §7", checked: "2026-09-27",
  },
  {
    table: "Scheme", id: "cmnfm3gn4003m3rxnrj7cifgp", op: "update",
    label: "Mumbai · Ramai Awas Gharkul Yojana",
    set: { amount: null },
    was: { amount: 250000 },
    why: "Hidden: unverifiable — Rs 2.5 lakh could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §7", checked: "2026-09-27",
  },
  {
    table: "Scheme", id: "cmocx56710003r2xn3rrp6q6c", op: "update",
    label: "Pune · Ramai Awas Gharkul Yojana",
    set: { amount: null },
    was: { amount: 250000 },
    why: "Hidden: unverifiable — Rs 2.5 lakh could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §7", checked: "2026-09-27",
  },
  {
    table: "Scheme", id: "cmmvn78cw00qpmuxn1rjg4o3y", op: "update",
    label: "Mysuru · PM Awas Yojana (Gramin)",
    set: { amount: null, beneficiaryCount: null },
    was: { amount: 130000, beneficiaryCount: 22000 },
    why: "Hidden: unverifiable — Rs 1.3 lakh differs from the plain-area PMAY-G amount and 22,000 beneficiaries have no source.",
    source: "none — see docs/DATA-FIXES-2026-09.md §7", checked: "2026-09-27",
  },
  {
    table: "Scheme", id: "cmmvn78cw00qrmuxn1hivs7ir", op: "update",
    label: "Mysuru · Sericulture Subsidy Scheme",
    set: { amount: null, beneficiaryCount: null },
    was: { amount: 50000, beneficiaryCount: 28000 },
    why: "Hidden: unverifiable — Rs 50,000 and 28,000 beneficiaries have no source.",
    source: "none — see docs/DATA-FIXES-2026-09.md §7", checked: "2026-09-27",
  },
  {
    table: "Scheme", id: "cmmvn78cw00qomuxn5qs130yn", op: "update",
    label: "Mysuru · Anna Bhagya",
    set: { amount: null, beneficiaryCount: null },
    was: { amount: 0, beneficiaryCount: 248000 },
    why: "Hidden: unverifiable — Rs 0 is not an amount and 2,48,000 beneficiaries have no source.",
    source: "none — see docs/DATA-FIXES-2026-09.md §7", checked: "2026-09-27",
  },
  {
    table: "Scheme", id: "cmmvn78cw00qumuxnp5gh1l2i", op: "update",
    label: "Mysuru · MGNREGA Mysuru",
    set: { amount: null, beneficiaryCount: null },
    was: { amount: 0, beneficiaryCount: 68000 },
    why: "Hidden: unverifiable — Rs 0 is not an amount and 68,000 beneficiaries have no source.",
    source: "none — see docs/DATA-FIXES-2026-09.md §7", checked: "2026-09-27",
  },
  {
    table: "Scheme", id: "cmmvn78cw00qmmuxno8s55rt1", op: "update",
    label: "Mysuru · Shakti Free Bus Pass",
    set: { amount: null, beneficiaryCount: null },
    was: { amount: 0, beneficiaryCount: 182000 },
    why: "Hidden: unverifiable — Rs 0 is not an amount and 1,82,000 beneficiaries have no source.",
    source: "none — see docs/DATA-FIXES-2026-09.md §7", checked: "2026-09-27",
  },
  {
    table: "Scheme", id: "cmmvn78cw00qlmuxnpkaud2e4", op: "update",
    label: "Mysuru · Gruha Lakshmi",
    set: { beneficiaryCount: null },
    was: { beneficiaryCount: 8530 },
    why: "Hidden: unverifiable — 8,530 beneficiaries is implausibly low for Gruha Lakshmi in Mysuru district and could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §7", checked: "2026-09-27",
  },
  {
    table: "Scheme", id: "cmmvn78cw00qnmuxnckvruc0r", op: "update",
    label: "Mysuru · Yuva Nidhi",
    set: { beneficiaryCount: null },
    was: { beneficiaryCount: 581 },
    why: "Hidden: unverifiable — 581 beneficiaries could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §7", checked: "2026-09-27",
  },
  {
    table: "Scheme", id: "cmnf0n6nd002o1dxn7vxoide8", op: "update",
    label: "New Delhi · Ladli Yojana (Girl Child)",
    set: { amount: null },
    was: { amount: 100000 },
    why: "Hidden: unverifiable — Rs 1 lakh could not be confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §7", checked: "2026-09-27",
  },
  {
    table: "Scheme", id: "cmnf0n6nd002i1dxna2eigv5b", op: "update",
    label: "New Delhi · PM-SVANidhi (Street Vendor)",
    set: { amount: null },
    was: { amount: 10000 },
    why: "Hidden: unverifiable — PM-SVANidhi loan slabs were revised; Rs 10,000 may be outdated and was not confirmed.",
    source: "none — see docs/DATA-FIXES-2026-09.md §7", checked: "2026-09-27",
  },
  {
    table: "Scheme", id: "cmnfm3oha00304exncighb9bo", op: "update",
    label: "Kolkata · Kanyashree Prakalpa",
    set: { beneficiaryCount: null },
    was: { beneficiaryCount: 50000 },
    why: "Hidden: unverifiable — 50,000 beneficiaries has no source.",
    source: "none — see docs/DATA-FIXES-2026-09.md §7", checked: "2026-09-27",
  },
  {
    table: "Scheme", id: "cmnfm3oha00324exnf90y7mwg", op: "update",
    label: "Kolkata · Lakshmir Bhandar",
    set: { beneficiaryCount: null },
    was: { beneficiaryCount: 200000 },
    why: "Hidden: unverifiable — 2,00,000 beneficiaries has no source.",
    source: "none — see docs/DATA-FIXES-2026-09.md §7", checked: "2026-09-27",
  },
  {
    table: "Scheme", id: "cmnfm3oha00314exn9zj3xo4i", op: "update",
    label: "Kolkata · Swasthya Sathi",
    set: { beneficiaryCount: null },
    was: { beneficiaryCount: 100000 },
    why: "Hidden: unverifiable — 1,00,000 beneficiaries has no source.",
    source: "none — see docs/DATA-FIXES-2026-09.md §7", checked: "2026-09-27",
  },
  {
    table: "Scheme", id: "cmnfm3se0003851xnic5l7ndq", op: "update",
    label: "Chennai · Kalaignar Magalir Urimai Thogai (Women's Right Grant)",
    set: { beneficiaryCount: null },
    was: { beneficiaryCount: 10000000 },
    why: "Hidden: unverifiable — 1,00,00,000 is a statewide order of magnitude stored on the Chennai district row; no source.",
    source: "none — see docs/DATA-FIXES-2026-09.md §7", checked: "2026-09-27",
  },
];
