/**
 * ForThePeople.in — Your District. Your Data. Your Right.
 * © 2026 Jayanth M B. MIT License with Attribution.
 * https://github.com/jayanthmb14/forthepeople
 */

// ═══════════════════════════════════════════════════════════
// Cron: Generate / refresh AI module insights
// GET or POST /api/cron/generate-insights
// Schedule: 00:00 and 12:00 UTC (vercel.json)
// Auth: verifyCron() — Bearer (Vercel) or x-cron-secret (manual)
// Processes all districts × modules where expiresAt < now
// Rate-limited: 2s delay between AI calls
//
// Sept 2026 fix: this route only checked "x-cron-secret", but Vercel Cron
// sends "Authorization: Bearer", so every scheduled run since 29 March
// returned 401 and no insight was ever generated by the scheduler.
// Run state is recorded in Redis "ftp:cron:generate-insights".
// ═══════════════════════════════════════════════════════════
import { NextRequest, NextResponse } from "next/server";
import * as Sentry from "@sentry/nextjs";
import { prisma } from "@/lib/db";
import { MODULE_INSIGHT_CONFIGS } from "@/lib/insight-config";
import { generateInsight, hasDataChanged } from "@/lib/insight-generator";
import { alertCronFailed } from "@/lib/admin-alerts";
import { selectProjectsNeedingAnalysis, generateInfraAnalysis } from "@/lib/infra-analysis";
import { verifyCron, cronStarted, cronFinished } from "@/lib/cron-auth";

const INFRA_ANALYSIS_CAP_PER_RUN = 10;
const CRON_NAME = "generate-insights";

export const runtime = "nodejs";
export const maxDuration = 300; // 5 min max

function sleep(ms: number) {
  return new Promise((r) => setTimeout(r, ms));
}

export async function POST(req: NextRequest) {
  // Auth check (accepts Bearer or x-cron-secret; fails closed)
  if (!verifyCron(req)) {
    return NextResponse.json({ error: "unauthorized" }, { status: 401 });
  }

  const startTime = await cronStarted(CRON_NAME);
  const results: { district: string; module: string; ok: boolean }[] = [];

  try {
    // Get all active districts
    const districts = await prisma.district.findMany({
      where: { active: true },
      select: { id: true, slug: true, name: true, state: { select: { slug: true, name: true } } },
    });

    // Find all expired or missing insights
    const now = new Date();

    for (const district of districts) {
      for (const config of MODULE_INSIGHT_CONFIGS) {
        // Check if insight exists and is still valid
        const existing = await prisma.aIModuleInsight.findUnique({
          where: { districtId_module: { districtId: district.id, module: config.module } },
          select: { expiresAt: true },
        });

        if (existing && existing.expiresAt > now) {
          // Still fresh — skip
          continue;
        }

        // April 13, 2026 — skip regeneration if underlying data hasn't changed
        // since the last insight. Static modules (leaders, budget, schools)
        // rarely change and were burning Gemini Pro calls on every run.
        // Exception (Apr 15 2026): the leaders module gets a hard 7-day TTL
        // even without data change so the page never shows >2-week-old
        // analysis. During an active election period (any ElectionEvent
        // with polling within 30 days for this district's state), the
        // leaders module refreshes daily.
        if (config.module === "leaders") {
          const electionLive = await prisma.electionEvent.findFirst({
            where: {
              isActive: true,
              state: district.state.slug,
              pollingDate: {
                gte: new Date(Date.now() - 1 * 86_400_000),
                lte: new Date(Date.now() + 30 * 86_400_000),
              },
            },
            select: { id: true },
          });
          const refreshAfterMs = electionLive ? 1 * 86_400_000 : 7 * 86_400_000;
          const generatedAt = existing ? new Date(existing.expiresAt.getTime() - 24 * 3600_000) : null;
          const ageMs = generatedAt ? Date.now() - generatedAt.getTime() : Infinity;
          if (ageMs < refreshAfterMs) {
            console.log(`[generate-insights] Skip leaders/${district.slug} — within TTL window (${electionLive ? "election-live 1d" : "default 7d"})`);
            continue;
          }
          // Fall through to regenerate, ignoring hasDataChanged for leaders.
        } else if (!(await hasDataChanged(district.id, config.module))) {
          console.log(
            `[generate-insights] Skip ${config.module}/${district.slug} — no data change`
          );
          continue;
        }

        // Generate new insight
        const ok = await generateInsight(
          config,
          district.id,
          district.slug,
          district.name,
          district.state.slug,
          district.state.name
        );

        results.push({ district: district.slug, module: config.module, ok });

        // 2-second delay between calls to respect Anthropic rate limits
        await sleep(2000);

        // Stop if approaching timeout
        if (Date.now() - startTime > 270_000) {
          console.log("[generate-insights] Approaching timeout, stopping early");
          break;
        }
      }
    }

    const succeeded = results.filter((r) => r.ok).length;
    const failed = results.filter((r) => !r.ok).length;

    // ── Pre-compute infra project analyses (zero user-triggered AI) ──
    // Pick up to 10 projects that have real (non-SEED) news updates and no
    // cached analysis; regenerate via Gemini 2.5 Pro and cache for 24h.
    let infraAnalysed = 0;
    let infraFailed = 0;
    try {
      const pending = await selectProjectsNeedingAnalysis(INFRA_ANALYSIS_CAP_PER_RUN);
      for (const projectId of pending) {
        if (Date.now() - startTime > 270_000) break;
        const out = await generateInfraAnalysis(projectId);
        if (out) infraAnalysed++; else infraFailed++;
        await sleep(2000);
      }
    } catch (err) {
      console.error("[generate-insights] infra analysis pass failed:", err);
    }

    // A run where every attempted insight failed means the AI layer is
    // down — record it as an error so /api/health reports "degraded".
    // A run with nothing to do (all insights still fresh) is a success.
    const allFailed = results.length > 0 && succeeded === 0;
    await cronFinished(CRON_NAME, startTime, {
      status: allFailed ? "error" : "ok",
      count: succeeded + infraAnalysed,
      error: allFailed ? `${failed} insight(s) attempted, 0 succeeded` : undefined,
    });

    return NextResponse.json({
      ok: true,
      processed: results.length,
      succeeded,
      failed,
      infra: { analysed: infraAnalysed, failed: infraFailed, cap: INFRA_ANALYSIS_CAP_PER_RUN },
      durationMs: Date.now() - startTime,
    });
  } catch (err) {
    Sentry.captureException(err);
    const msg = err instanceof Error ? err.message : String(err);
    alertCronFailed(CRON_NAME, msg).catch(() => {});
    console.error("[generate-insights] Fatal:", err);
    await cronFinished(CRON_NAME, startTime, { status: "error", error: msg });
    return NextResponse.json({ ok: false, error: msg }, { status: 500 });
  }
}

// Vercel cron calls via GET
export async function GET(req: NextRequest) {
  return POST(req);
}
