/**
 * ForThePeople.in — Your District. Your Data. Your Right.
 * © 2026 Jayanth M B. MIT License.
 * https://github.com/jayanthmb14/forthepeople
 */

// ═══════════════════════════════════════════════════════════
// Cron: Generate / refresh AI module insights
// GET or POST /api/cron/generate-insights
// Schedule: 00:00 and 12:00 UTC (vercel.json)
// Auth: verifyCron() — Bearer (Vercel) or x-cron-secret (manual)
// Processes all districts × modules where expiresAt < now
// Rate-limited: 2s delay between AI calls
//
// v5: the work list (missing or expired insights) is built up front and
// sorted oldest-expired first, so a run cut short by its time budget never
// starves the same districts twice; the deadline check now ends the WHOLE
// run (it used to leave only the inner module loop, so new AI calls kept
// starting after 270 s); modules with no data are skipped without an AI
// call (see src/lib/insight-generator.ts).
//
// Sept 2026 fix: this route only checked "x-cron-secret", but Vercel Cron
// sends "Authorization: Bearer", so every scheduled run since 29 March
// returned 401 and no insight was ever generated by the scheduler.
// Run state is recorded in Redis "ftp:cron:generate-insights".
// ═══════════════════════════════════════════════════════════
import { NextRequest, NextResponse } from "next/server";
import * as Sentry from "@sentry/nextjs";
import { prisma } from "@/lib/db";
import { MODULE_INSIGHT_CONFIGS } from "@/lib/insight-config";
import { generateInsightDetailed, hasDataChanged } from "@/lib/insight-generator";
import { alertCronFailed } from "@/lib/admin-alerts";
import { selectProjectsNeedingAnalysis, generateInfraAnalysis } from "@/lib/infra-analysis";
import { translatePendingContent } from "@/lib/translation/job";
import { verifyCron, cronStarted, cronFinished } from "@/lib/cron-auth";
import { insightExpired, leadersNeedsRefresh } from "@/lib/insight-refresh";

const INFRA_ANALYSIS_CAP_PER_RUN = 10;
const CRON_NAME = "generate-insights";
/** No new module insight starts after this… */
const INSIGHTS_BUDGET_MS = 230_000;
/** …and no infra analysis after this (translation gets what is left of 270 s). */
const INFRA_BUDGET_MS = 255_000;

export const runtime = "nodejs";
export const maxDuration = 300; // 5 min max

function sleep(ms: number) {
  return new Promise((r) => setTimeout(r, ms));
}

export async function POST(req: NextRequest) {
  // Auth check (accepts Bearer or x-cron-secret; fails closed)
  if (!verifyCron(req)) {
    return NextResponse.json({ error: "unauthorized" }, { status: 401 });
  }

  const startTime = await cronStarted(CRON_NAME);
  const insightsDeadline = startTime + INSIGHTS_BUDGET_MS;
  const results: { district: string; module: string; ok: boolean; error?: string }[] = [];
  const skipped = { fresh: 0, noChange: 0, emptyData: 0, notReached: 0 };

  try {
    // Get all active districts
    const districts = await prisma.district.findMany({
      where: { active: true },
      select: { id: true, slug: true, name: true, state: { select: { slug: true, name: true } } },
    });

    // Existing insights in ONE query, then the work list: missing or expired,
    // oldest-expired first (missing = never generated = first of all).
    const now = new Date();
    const existingRows = await prisma.aIModuleInsight.findMany({
      where: { districtId: { in: districts.map((d) => d.id) } },
      select: { districtId: true, module: true, expiresAt: true, generatedAt: true },
    });
    const timesOf = new Map(existingRows.map((r) => [`${r.districtId}:${r.module}`, r]));

    // Leaders (Apr 15 2026): hard 7-day age limit, daily during an active
    // election period (any active ElectionEvent polling within 30 days for
    // the district's state) — see src/lib/insight-refresh.ts.
    const liveElectionStates = new Set(
      (
        await prisma.electionEvent.findMany({
          where: {
            isActive: true,
            state: { in: [...new Set(districts.map((d) => d.state.slug))] },
            pollingDate: {
              gte: new Date(now.getTime() - 1 * 86_400_000),
              lte: new Date(now.getTime() + 30 * 86_400_000),
            },
          },
          select: { state: true },
          take: 500,
        })
      ).map((e) => e.state),
    );

    const work: Array<{ district: (typeof districts)[number]; config: (typeof MODULE_INSIGHT_CONFIGS)[number]; expiresAt: Date | null }> = [];
    for (const district of districts) {
      for (const config of MODULE_INSIGHT_CONFIGS) {
        const row = timesOf.get(`${district.id}:${config.module}`);
        const times = { generatedAt: row?.generatedAt ?? null, expiresAt: row?.expiresAt ?? null };
        const due =
          config.module === "leaders"
            ? leadersNeedsRefresh({ ...times, electionLive: liveElectionStates.has(district.state.slug), now })
            : insightExpired(times, now);
        if (!due) {
          skipped.fresh++;
          continue;
        }
        work.push({ district, config, expiresAt: times.expiresAt });
      }
    }
    work.sort((a, b) => (a.expiresAt?.getTime() ?? -Infinity) - (b.expiresAt?.getTime() ?? -Infinity));

    for (let i = 0; i < work.length; i++) {
      // One deadline check that ends the whole run (not just one district).
      if (Date.now() >= insightsDeadline) {
        skipped.notReached = work.length - i;
        console.log(`[generate-insights] Time budget used; ${skipped.notReached} insight(s) left for the next run`);
        break;
      }
      const { district, config } = work[i];

      // April 13, 2026 — skip regeneration if underlying data hasn't changed
      // since the last insight. Static modules (budget, schools) rarely
      // change and were burning paid calls on every run. Leaders are on the
      // work list only when their age limit says so (above), and then
      // regenerate whether or not the data changed.
      if (config.module !== "leaders" && !(await hasDataChanged(district.id, config.module))) {
        skipped.noChange++;
        continue;
      }

      const outcome = await generateInsightDetailed(
        config,
        district.id,
        district.slug,
        district.name,
        district.state.slug,
        district.state.name,
        { deadlineAt: insightsDeadline },
      );
      if (outcome.status === "empty") {
        skipped.emptyData++;
        continue; // no AI call was made
      }
      results.push({
        district: district.slug,
        module: config.module,
        ok: outcome.status === "ok",
        error: outcome.status === "error" ? outcome.error.slice(0, 200) : undefined,
      });

      // 2-second pause between AI calls to stay under provider rate limits
      await sleep(2000);
    }

    const succeeded = results.filter((r) => r.ok).length;
    const failed = results.filter((r) => !r.ok).length;

    // ── Pre-compute infra project analyses (zero user-triggered AI) ──
    // Pick up to 10 projects that have real (non-SEED) news updates and no
    // cached analysis; regenerate via Gemini 2.5 Pro and cache for 24h.
    let infraAnalysed = 0;
    let infraFailed = 0;
    try {
      const pending = await selectProjectsNeedingAnalysis(INFRA_ANALYSIS_CAP_PER_RUN);
      for (const projectId of pending) {
        if (Date.now() - startTime > INFRA_BUDGET_MS) break;
        const out = await generateInfraAnalysis(projectId);
        if (out) infraAnalysed++; else infraFailed++;
        await sleep(2000);
      }
    } catch (err) {
      console.error("[generate-insights] infra analysis pass failed:", err);
    }

    // A run where every attempted insight failed means the AI layer is
    // down — record it as an error so /api/health reports "degraded".
    // A run with nothing to do (all insights still fresh) is a success.
    const allFailed = results.length > 0 && succeeded === 0;
    const firstError = results.find((r) => r.error)?.error;
    await cronFinished(CRON_NAME, startTime, {
      status: allFailed ? "error" : "ok",
      count: succeeded + infraAnalysed,
      error: allFailed ? `${failed} insight(s) attempted, 0 succeeded. ${firstError ?? ""}`.trim() : undefined,
    });
    if (allFailed) alertCronFailed(CRON_NAME, `${failed} insight(s) attempted, 0 succeeded. ${firstError ?? ""}`.trim()).catch(() => {});

    // Translate the new insights once into every switched-on language
    // (stored; see src/lib/translation). Leftovers go to translate-content.
    let translation: Awaited<ReturnType<typeof translatePendingContent>> | null = null;
    const timeLeft = 270_000 - (Date.now() - startTime);
    if (succeeded > 0 && timeLeft > 20_000) {
      translation = await translatePendingContent({ budgetMs: timeLeft - 10_000 }).catch(() => null);
    }

    return NextResponse.json({
      ok: true,
      processed: results.length,
      succeeded,
      failed,
      skipped,
      errors: results.filter((r) => r.error).slice(0, 5),
      infra: { analysed: infraAnalysed, failed: infraFailed, cap: INFRA_ANALYSIS_CAP_PER_RUN },
      translation,
      durationMs: Date.now() - startTime,
    });
  } catch (err) {
    Sentry.captureException(err);
    const msg = err instanceof Error ? err.message : String(err);
    alertCronFailed(CRON_NAME, msg).catch(() => {});
    console.error("[generate-insights] Fatal:", err);
    await cronFinished(CRON_NAME, startTime, { status: "error", error: msg });
    return NextResponse.json({ ok: false, error: msg }, { status: 500 });
  }
}

// Vercel cron calls via GET
export async function GET(req: NextRequest) {
  return POST(req);
}
