/**
 * ForThePeople.in — Your District. Your Data. Your Right.
 * © 2026 Jayanth M B. MIT License.
 * https://github.com/jayanthmb14/forthepeople
 */

import { ROUTED_LOCALES } from "@/i18n/languages";
import type { Metadata } from "next";
import { fontVariableClasses } from "@/lib/fonts";
import Script from "next/script";
import {
  getCoveragePhrase,
  getCoverageSentence,
  getPlatformFacts,
} from "@/lib/platform-facts";
import "./globals.css";

const BASE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "https://forthepeople.in";

// One source for every count printed below (districts, states, modules).
// See src/lib/platform-facts.ts — fixes GitHub issue #36.
const FACTS = getPlatformFacts();

// The social-preview image is generated by src/app/[locale]/opengraph-image.tsx
// (Next.js file convention). There is NO static /og-image.png in /public —
// the old reference to it returned the homepage HTML, which social crawlers
// rejected. Point every share card at the real route instead.
const OG_IMAGE_URL = "/en/opengraph-image";

export const metadata: Metadata = {
  title: {
    default: "ForThePeople.in — Your District. Your Data. Your Right.",
    template: "%s | ForThePeople.in",
  },
  description:
    "India's citizen transparency platform. Access district-level government data — budgets, schemes, crop prices, water levels, and more.",
  metadataBase: new URL(BASE_URL),
  keywords: [
    "government data India", "district dashboard", "RTI India",
    "crop prices", "government schemes", "citizen transparency",
    "district dashboard", "Hyderabad", "gram panchayat",
    "India civic data", "public data India", "government transparency",
  ],
  authors: [{ name: "Jayanth M B", url: BASE_URL }],
  creator: "Jayanth M B",
  publisher: "ForThePeople.in",
  other: {
    "original-author": "Jayanth M B",
    "project-inception": "2026-03-17",
    "x-created-by": "Jayanth M B, Karnataka, India",
    "x-project-id": "FTP-JMB-2026-IN",
    "x-repository": "github.com/jayanthmb14/forthepeople",
  },
  openGraph: {
    type: "website",
    siteName: "ForThePeople.in",
    title: "ForThePeople.in — Your District. Your Data. Your Right.",
    description:
      "Access district-level government data for every Indian — budgets, crop prices, water levels, schemes, and more.",
    url: BASE_URL,
    images: [
      {
        url: OG_IMAGE_URL,
        width: 1200,
        height: 630,
        alt: "ForThePeople.in — District Data Platform for India",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "ForThePeople.in — Your District. Your Data. Your Right.",
    description: "Independent citizen transparency platform aggregating government data, research institution datasets, and verified public sources for Indian districts. NOT an official government service.",
    images: [OG_IMAGE_URL],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large" },
  },
};

// WebApplication schema — creator attribution for search engines
const webAppLd = {
  "@context": "https://schema.org",
  "@type": "WebApplication",
  "name": "ForThePeople.in",
  "url": BASE_URL,
  "description": "India's Citizen Transparency Platform — free, source-linked district-level government data dashboards",
  "applicationCategory": "GovernmentService",
  "operatingSystem": "Web",
  "dateCreated": "2026-03-17",
  "license": "https://opensource.org/licenses/MIT",
  "isAccessibleForFree": true,
  "inLanguage": ROUTED_LOCALES,
  "author": {
    "@type": "Person",
    "name": "Jayanth M B",
    "url": "https://www.instagram.com/jayanth_m_b/",
    "nationality": "Indian",
    "address": {
      "@type": "PostalAddress",
      "addressRegion": "Karnataka",
      "addressCountry": "IN",
    },
  },
};

// Organization + WebSite + FAQPage schema for all pages
const organizationLd = {
  "@context": "https://schema.org",
  "@type": "Organization",
  "name": "ForThePeople.in",
  "url": BASE_URL,
  "logo": `${BASE_URL}/android-chrome-512x512.png`,
  "description": "India's citizen transparency platform providing free district-level government data — budgets, crop prices, water levels, government schemes, and more.",
  "foundingDate": "2026",
  "founder": {
    "@type": "Person",
    "name": "Jayanth M B",
    "url": BASE_URL,
  },
  "areaServed": {
    "@type": "Country",
    "name": "India",
  },
  "sameAs": [],
};

const websiteLd = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  "name": "ForThePeople.in",
  "url": BASE_URL,
  "description": "India's citizen transparency platform. Access district-level government data free of cost.",
  "inLanguage": ROUTED_LOCALES,
  "potentialAction": {
    "@type": "SearchAction",
    "target": {
      "@type": "EntryPoint",
      "urlTemplate": `${BASE_URL}/en?q={search_term_string}`,
    },
    "query-input": "required name=search_term_string",
  },
};

const faqLd = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  "mainEntity": [
    {
      "@type": "Question",
      "name": "What is ForThePeople.in?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "ForThePeople.in is India's citizen transparency platform — a free, independent website that aggregates district-level government data including crop prices, dam water levels, government schemes, budgets, school data, and more. It is not an official government website and operates under the NDSAP Open Data Policy.",
      },
    },
    {
      "@type": "Question",
      "name": "Which districts are covered on ForThePeople.in?",
      "acceptedAnswer": {
        "@type": "Answer",
        // Generated from the district registry so this answer can never drift
        // from the homepage again (issue #36).
        "text": `ForThePeople.in currently covers ${getCoveragePhrase()}: ${getCoverageSentence()}. The platform plans to expand to all ${FACTS.totalIndiaDistricts} Indian districts. Each district has ${FACTS.modulesPerDistrict} data modules covering weather, crops, water, budget, schools, elections, leadership and other civic categories, each linked to its official source.`,
      },
    },
    {
      "@type": "Question",
      "name": "How do I check crop prices on ForThePeople.in?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "To check crop prices, navigate to your district page (e.g., forthepeople.in/en/karnataka/mandya) and click on 'Crop Prices'. Mandi prices are sourced from AGMARKNET and refreshed whenever the portal publishes new rows; every price shows the market and the date it was recorded. You can view prices for paddy, sugarcane, ragi, jowar, maize, and other crops with historical trends.",
      },
    },
    {
      "@type": "Question",
      "name": "How do I file an RTI using ForThePeople.in?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "ForThePeople.in provides RTI (Right to Information) templates and filing guides for every district. Navigate to your district, click 'RTI', and you'll find pre-filled templates for common government data requests. You can submit RTIs through the official RTI Online Portal at rtionline.gov.in.",
      },
    },
    {
      "@type": "Question",
      "name": "Is ForThePeople.in data free to access?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "Yes. ForThePeople.in is completely free — no paywalls, no subscriptions, no registration required. All government data belongs to citizens. The platform sources data from official government portals, public APIs, and gazetted documents under the National Data Sharing and Accessibility Policy (NDSAP).",
      },
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={fontVariableClasses}
      // [locale]/layout.tsx sets lang/dir on <html> before hydration.
      suppressHydrationWarning
    >
      <head>
        <meta name="theme-color" content="#2563EB" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="ForThePeople" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
      </head>
      <body className="antialiased">
        {/* The skip link is rendered by [locale]/layout.tsx, in the page language. */}
        {/* Global structured data */}
        <Script
          id="webapp-jsonld"
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(webAppLd) }}
        />
        <Script
          id="org-jsonld"
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationLd) }}
        />
        <Script
          id="website-jsonld"
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteLd) }}
        />
        <Script
          id="faq-jsonld"
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(faqLd) }}
        />
        {process.env.NEXT_PUBLIC_PLAUSIBLE_DOMAIN && (
          <Script
            defer
            data-domain={process.env.NEXT_PUBLIC_PLAUSIBLE_DOMAIN}
            src="https://plausible.io/js/script.js"
            strategy="afterInteractive"
          />
        )}
        {children}
        {/* Service worker on real hosts only. On localhost it cached the
            offline page, which then showed whenever the local server stopped. */}
        <script
          dangerouslySetInnerHTML={{
            __html: `if ('serviceWorker' in navigator) { var h = location.hostname; if (h === 'localhost' || h === '127.0.0.1' || h.endsWith('.local')) { navigator.serviceWorker.getRegistrations().then(function (rs) { rs.forEach(function (r) { r.unregister(); }); }); } else { window.addEventListener('load', function () { navigator.serviceWorker.register('/sw.js'); }); } }`,
          }}
        />
              </body>
    </html>
  );
}
