/**
 * ForThePeople.in — Your District. Your Data. Your Right.
 * © 2026 Jayanth M B. MIT License.
 *
 * Infrastructure Tracker — cached AI analysis for one project (never triggers AI on render).
 * Design v3: a plain Card with a Sparkles icon in the features accent.
 */

"use client";

import { useQuery } from "@tanstack/react-query";
import { Sparkles } from "lucide-react";
import { Card } from "@/components/district/ui";

export interface InfraAnalysis {
  citizenImpact: string[];
  accountability: string[];
  notes: string;
  sources: number;
  generatedAt: string;
  cached: boolean;
  unavailable?: boolean;
}

/** Small uppercase heading used inside the analysis card. */
const SUBHEAD: React.CSSProperties = {
  fontSize: 11, lineHeight: "16px", fontWeight: 500, color: "var(--ftp-text-2)",
  letterSpacing: "0.04em", textTransform: "uppercase", marginBottom: 4,
};
const LIST: React.CSSProperties = {
  margin: "0 0 10px", paddingLeft: 16, fontSize: 13, lineHeight: "20px", color: "var(--ftp-text)",
};

/**
 * Pre-computed analysis reader. NEVER triggers AI on render — the
 * analysis is generated offline by /api/cron/generate-insights and
 * cached in Redis for 24h. If no cache entry exists, the UI renders a
 * calm "Analysis will be available soon" placeholder instead of a
 * click-to-spend button.
 */
export default function PrecomputedAnalysis({ projectId }: { projectId: string }) {
  const { data, isFetching } = useQuery<InfraAnalysis>({
    queryKey: ["infra-analysis", projectId],
    queryFn: async () => {
      const res = await fetch(`/api/data/infra-analysis?projectId=${projectId}`);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      return res.json();
    },
    staleTime: 60 * 60_000,
  });

  if (isFetching && !data) {
    return (
      <p className="ftp-body" style={{ color: "var(--ftp-text-2)" }}>
        Loading analysis…
      </p>
    );
  }
  if (!data || data.unavailable) {
    return (
      <Card padding={14}>
        <p className="ftp-body" style={{ color: "var(--ftp-text-2)" }}>
          AI analysis will be available soon — generated in the background once
          this project has news coverage.
        </p>
      </Card>
    );
  }

  return (
    <Card padding={14}>
      <div style={{ display: "flex", alignItems: "center", gap: 6, marginBottom: 10 }}>
        <Sparkles size={14} aria-hidden style={{ color: "var(--ftp-features)" }} />
        <span style={{ ...SUBHEAD, marginBottom: 0, color: "var(--ftp-text)" }}>Project Analysis</span>
      </div>
      {data.citizenImpact?.length > 0 && (
        <>
          <div style={SUBHEAD}>For Citizens</div>
          <ul style={LIST}>
            {data.citizenImpact.map((s, i) => <li key={i}>{s}</li>)}
          </ul>
        </>
      )}
      {data.accountability?.length > 0 && (
        <>
          <div style={SUBHEAD}>For Accountability</div>
          <ul style={LIST}>
            {data.accountability.map((s, i) => <li key={i}>{s}</li>)}
          </ul>
        </>
      )}
      {data.notes && <div style={{ fontSize: 11, lineHeight: "16px", color: "var(--ftp-text-2)" }}>{data.notes}</div>}
      <div style={{ marginTop: 8, fontSize: 11, lineHeight: "16px", color: "var(--ftp-text-2)" }}>
        Source: <span className="ftp-num">{data.sources}</span> news articles · Generated by Gemini 2.5 Pro · ForThePeople.in
      </div>
    </Card>
  );
}
