/**
 * ForThePeople.in — Your District. Your Data. Your Right.
 * © 2026 Jayanth M B. MIT License.
 *
 * Infrastructure Tracker — cached AI analysis for one project (never triggers AI on render).
 * Extracted from infrastructure/page.tsx (no behaviour change).
 */

"use client";

import { useQuery } from "@tanstack/react-query";
import { Sparkles } from "lucide-react";

export interface InfraAnalysis {
  citizenImpact: string[];
  accountability: string[];
  notes: string;
  sources: number;
  generatedAt: string;
  cached: boolean;
  unavailable?: boolean;
}

/**
 * Pre-computed analysis reader. NEVER triggers AI on render — the
 * analysis is generated offline by /api/cron/generate-insights and
 * cached in Redis for 24h. If no cache entry exists, the UI renders a
 * calm "Analysis will be available soon" placeholder instead of a
 * click-to-spend button.
 */
export default function PrecomputedAnalysis({ projectId }: { projectId: string }) {
  const { data, isFetching } = useQuery<InfraAnalysis>({
    queryKey: ["infra-analysis", projectId],
    queryFn: async () => {
      const res = await fetch(`/api/data/infra-analysis?projectId=${projectId}`);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      return res.json();
    },
    staleTime: 60 * 60_000,
  });

  if (isFetching && !data) {
    return (
      <div style={{ padding: "10px 14px", background: "#F5F5F0", borderRadius: 10, fontSize: 12, color: "#6B7280" }}>
        Loading analysis…
      </div>
    );
  }
  if (!data || data.unavailable) {
    return (
      <div
        style={{
          padding: "10px 14px",
          background: "#FAFAFA",
          border: "1px dashed #E5E7EB",
          borderRadius: 10,
          fontSize: 12,
          color: "#9CA3AF",
          fontStyle: "italic",
        }}
      >
        AI analysis will be available soon — generated in the background once
        this project has news coverage.
      </div>
    );
  }

  return (
    <div style={{ padding: "14px 16px", background: "#FAFAFE", border: "1px solid #E0E7FF", borderLeft: "4px solid #7C3AED", borderRadius: 12 }}>
      <div style={{ display: "flex", alignItems: "center", gap: 6, marginBottom: 10 }}>
        <Sparkles size={13} style={{ color: "#7C3AED" }} />
        <span style={{ fontSize: 12, fontWeight: 700, color: "#4C1D95", letterSpacing: "0.04em", textTransform: "uppercase" }}>
          Project Analysis
        </span>
      </div>
      {data.citizenImpact?.length > 0 && (
        <>
          <div style={{ fontSize: 11, fontWeight: 700, color: "#6B7280", marginBottom: 4, letterSpacing: "0.04em", textTransform: "uppercase" }}>📊 For Citizens</div>
          <ul style={{ margin: 0, paddingLeft: 16, fontSize: 12, color: "#374151", lineHeight: 1.6, marginBottom: 10 }}>
            {data.citizenImpact.map((s, i) => <li key={i}>{s}</li>)}
          </ul>
        </>
      )}
      {data.accountability?.length > 0 && (
        <>
          <div style={{ fontSize: 11, fontWeight: 700, color: "#6B7280", marginBottom: 4, letterSpacing: "0.04em", textTransform: "uppercase" }}>📊 For Accountability</div>
          <ul style={{ margin: 0, paddingLeft: 16, fontSize: 12, color: "#374151", lineHeight: 1.6, marginBottom: 10 }}>
            {data.accountability.map((s, i) => <li key={i}>{s}</li>)}
          </ul>
        </>
      )}
      {data.notes && <div style={{ fontSize: 11, color: "#6B7280", lineHeight: 1.5, fontStyle: "italic" }}>{data.notes}</div>}
      <div style={{ marginTop: 8, fontSize: 10, color: "#9B9B9B" }}>
        Source: {data.sources} news articles · Generated by Gemini 2.5 Pro · ForThePeople.in
      </div>
    </div>
  );
}
