/**
 * ForThePeople.in — Your District. Your Data. Your Right.
 * © 2026 Jayanth M B. MIT License.
 * https://github.com/jayanthmb14/forthepeople
 */

// ═══════════════════════════════════════════════════════════
// ForThePeople.in — Real-time AI Module Insight (READ-ONLY)
// GET /api/ai/insight?module=weather&district=mandya
// Returns { opinion, severity, recommendation, generatedAt }
// Serves ONLY from Redis cache — never generates live AI on public GET.
// Live AI generation is restricted to backend crons and admins only.
// ═══════════════════════════════════════════════════════════
import { NextRequest, NextResponse } from "next/server";
import { cacheGet } from "@/lib/cache";

const CACHE_TTL = 30 * 60; // 30 minutes — must match cron generation frequency

// ── Route handler — READ-ONLY (public) ────────────────────
// NEVER calls live AI. Serves only from Redis cache.
// Pre-computed insights are generated by /api/cron/generate-insights.
// Public users cannot trigger AI billing.
export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url);
  const moduleSlug = searchParams.get("module");
  const districtSlug = searchParams.get("district");

  if (!moduleSlug || !districtSlug) {
    return NextResponse.json({ error: "module and district params required" }, { status: 400 });
  }

  const SUPPORTED_MODULES = ["weather", "crops", "water", "power", "police", "finance", "overview"];
  if (!SUPPORTED_MODULES.includes(moduleSlug)) {
    return NextResponse.json({ insight: null });
  }

  const cacheKeyStr = `ftp:ai:insight:${districtSlug}:${moduleSlug}`;

  const cached = await cacheGet<{
    opinion: string; severity: string; recommendation: string;
    generatedAt: string; aiProvider?: string; aiModel?: string;
  }>(cacheKeyStr);

  if (cached) {
    return NextResponse.json(
      { insight: cached, fromCache: true },
      { headers: { "Cache-Control": `public, s-maxage=${CACHE_TTL}, stale-while-revalidate=${CACHE_TTL * 2}` } }
    );
  }

  // Zero-credit guarantee: return null instead of generating live AI
  return NextResponse.json({ insight: null });
}
