/**
 * ForThePeople.in — Your District. Your Data. Your Right.
 * © 2026 Jayanth M B. MIT License.
 *
 * Data fixes for the September 2026 audit — NEWS area and the district
 * overview's number tiles and cards. Rule: verified or hidden. Every change
 * below comes from a finding an independent verifier confirmed; the code
 * that made each error was fixed first (see CHANGELOG, v5.4 news fixes), so
 * this only clears what that code already wrote.
 *
 * DRY RUN by default: prints every change (table, id, field, current → new,
 * source) and exits. Pass --confirm to apply everything in ONE transaction.
 *
 *   npx tsx scripts/fix-audit-2026-09-news.ts            # dry run
 *   npx tsx scripts/fix-audit-2026-09-news.ts --confirm  # apply
 *
 * Rows are matched by id. A row already gone, or a field already holding
 * the new value, is skipped. A row whose current value differs from the
 * value seen on 2026-09-28 (neither old nor new) is skipped and flagged
 * "CHANGED SINCE CHECK" — look at it by hand. Deletes check the row's
 * title/sector first the same way.
 *
 * What it does (finding numbers from the audit's news.json):
 *   LocalAlert     HIDE (active=false) the 13 active rows the old news
 *                  engine made from headlines (#0, #1).
 *   NewsItem       DELETE stories about another district/state (#13, #14)
 *                  and advertorials / price pages (#18); UPDATE duplicateOf
 *                  so one story shows once (#16); UPDATE category and
 *                  targetModule of the rows tagged by the old substring
 *                  classifier (#15).
 *   BudgetEntry    DELETE the hand-seeded rows of New Delhi, Mumbai,
 *                  Lucknow, Bengaluru Urban and Hyderabad (#8).
 *   GovernmentExam HIDE (null) the invented exam date and vacancies of
 *                  three April seed rows (#10, #11).
 *   InfraProject   DELETE "Ambedkar Memorial, Lucknow — Announced": the
 *                  memorial opened in 2008 (#3); its InfraUpdate goes with it
 *                  (onDelete: Cascade).
 *   District       UPDATE talukCount to the district portal's number, or
 *                  HIDE (null) where our units were invented (#6, #7).
 *   Taluk          UPDATE "Lucknow City" → "Lucknow Sadar" (#7).
 * Not here: leaders (Khairatabad MLA — owner to decide), election events.
 * After --confirm: clear the Redis caches (admin → Cache).
 */
import "./_env"; // MUST be first: loads .env + .env.local before any module reads process.env
import { PrismaClient } from "../src/generated/prisma";
import { PrismaPg } from "@prisma/adapter-pg";

const CONFIRM = process.argv.includes("--confirm");
const CHECKED = "2026-09-28";

type Value = string | number | boolean | null;
interface Fix {
  table: "LocalAlert" | "NewsItem" | "BudgetEntry" | "GovernmentExam" | "InfraProject" | "District" | "Taluk";
  id: string;
  op: "update" | "delete";
  /** update: field → new value. */
  set?: Record<string, Value>;
  /** The value(s) seen on 2026-09-28; a different current value skips the fix. */
  was: Record<string, Value>;
  /** "hide" when the new value only hides (null / active=false). */
  kind: "update" | "hide" | "delete";
  label: string;
  why: string;
  source: string;
}

const FIXES: Fix[] = [];

// ── LocalAlert: 13 news stories shown as "Warnings now" (#0, #1) ─────────
const NEWS_ALERT_WHY =
  "Made from a news story by the old news engine (autoGenerated, severity info) — not an official warning. News no longer writes LocalAlert (src/lib/news-action-engine.ts).";
const NEWS_ALERTS: Array<[string, string, string]> = [
  ["cmuk1fq2b001a2yxncm63gtw3", "chennai", "Action sought against CM Vijay and minister Aadhav Arjuna for violatin"],
  ["cmuk1dvby000u2yxn9xkle9ll", "chennai", "Aarthi Scans & Labs Ranked #1 in Diagnostics"],
  ["cmuk1sdpy00582yxn59l9ohzq", "hyderabad", "Childhood Cancer Survivors Awareness Programme in Hyderabad"],
  ["cmuk1og6b00432yxnrgzebsap", "hyderabad", "Organ donation saves lives in Hyderabad"],
  ["cmuk1y4aa00722yxnouqukyxh", "kolkata", "Opposition unity sought for removal of CEC Gyanesh Kumar"],
  ["cmuk1woeg006j2yxnny49gkoo", "kolkata", "Claim of 27 lakh voter deletions in West Bengal"],
  ["cmuk21xk8008x2yxnfw1jssfv", "mumbai", "Allegation of ECI 'match-fixing' in Maharashtra assembly elections"],
  ["cmuk1z25s00872yxn8mqp1e1k", "mumbai", "Maharashtra SIR deadline extended"],
  ["cmuk20qmd008l2yxnun3zzk9j", "mumbai", "ECI eases SIR notice process"],
  ["cmuk20wpp008o2yxnwkklk98m", "mumbai", "Suspected chemical exposure deaths in Mumbai public toilet"],
  ["cmuk222p000902yxnzo94vju2", "mumbai", "Health screening campaign"],
  ["cmuk23c0l009c2yxn6sjho1la", "mumbai", "Maharashtra to revive student elections after 33-year hiatus"],
  ["cmuk23htt009f2yxnbfa4dar2", "mumbai", "Chemical leak in Mumbai public toilet"],
];
for (const [id, district, title] of NEWS_ALERTS) {
  FIXES.push({
    table: "LocalAlert", id, op: "update", kind: "hide",
    set: { active: false }, was: { active: true, autoGenerated: true },
    label: `${district}: "${title}"`,
    why: NEWS_ALERT_WHY,
    source: `http://localhost:3000/api/data/alerts?district=${district} (verifier, ${CHECKED})`,
  });
}

// ── NewsItem: stories about another place (#13, #14) ─────────────────────
const OTHER_PLACE: Array<[string, string, string, string]> = [
  // [id, district, title prefix (checked), why]
  ["cmuhzf42x006704jpprtmoiqg", "new-delhi", "Gulbarga Tur Dal flagged off from Karnataka", "About Karnataka (Kalaburagi), not New Delhi."],
  ["cmugjz87y006604i4kq2fuytt", "new-delhi", "All-party delegation will visit Delhi to seek drought relief for Karnataka", "About Karnataka."],
  ["cmugjz8d5006704i4yxtdhjaz", "new-delhi", "In Karnataka job fraud case", "About Karnataka."],
  ["cmuf4jfr3006704l6h6ymgyjc", "new-delhi", "BJP Protests in Bengaluru Over Karnataka", "About Karnataka."],
  ["cmudp3k8e004u04l8zg0h3rd0", "new-delhi", "Delhi Confidential: Centre’s lawyer defends Karnataka", "About Karnataka's government."],
  ["cmudp3kdo004v04l86domud5j", "new-delhi", "Cauvery dispute: SC declines fresh plea", "About Karnataka's Cauvery share."],
  ["cmuc9nscc006c04jmjum41pit", "new-delhi", "With shortage in hydel and wind energy, KPCL", "About Karnataka Power Corporation."],
  ["cmuc9nrby006004jmhe7fwxd3", "new-delhi", "Rs 165-crore plan to build pucca schools in 5 areas in NE, east Delhi", "About North East and East Delhi districts."],
  ["cmugjz9ok006k04i4h9g5p69y", "new-delhi", "Delhi Police wake up after minor's gangrape", "About Central Delhi district."],
  ["cmuk1ica900212yxn6nh9d0pe", "chennai", "‘A pedestrian signal is needed at MM Nagar", "Maraimalai Nagar is in Chengalpattu district."],
  ["cmuk1icvx00252yxnzsvvgece", "chennai", "No pavements on this stretch", "Potheri is in Chengalpattu district."],
  ["cmuk1id0o00262yxn6ty9zwca", "chennai", "Not all visitors to Chitlapakkam Lake", "Chitlapakkam is in Chengalpattu district."],
  ["cmuk1idf700292yxn9xw80zqz", "chennai", "A dubious rarity", "About Mudichur, Chengalpattu district."],
  ["cmuk1id5k00272yxnt0s2j7e1", "chennai", "Greenfield shipyard in Thoothukudi", "About Thoothukudi district."],
  ["cmuk1hkmk001s2yxn1dyg4v26", "chennai", "Keeladi Museum Drives Archaeology Tourism", "Keeladi is in Sivaganga district."],
  ["cmugjyctg000i04i4zkt03r2k", "chennai", "Looms fall silent in Kongu Nadu", "About western Tamil Nadu (Kongu Nadu)."],
  ["cmuhze6l9000p04jpj4d9kkeb", "chennai", "Four from Pune killed in Bengaluru-Chennai Expressway crash", "Pune residents, crash outside Chennai district (the Pune copy stays)."],
  ["cmujeu9l7001204jxr75d5055", "kolkata", "South Tripura first in state", "About Tripura."],
  ["cmuhzeihg002z04jpl5tkznmz", "kolkata", "ER launches real-time level-crossing monitoring system in Murshidabad", "About Murshidabad district."],
  ["cmugjz3n2005k04i4mfdwh7vw", "mysuru", "Mandya farmers protest Cauvery water release", "About Mandya district (the Mandya copy stays)."],
  ["cmuhzf0jw005c04jpibmc8ylt", "mysuru", "Chikkamagaluru to tune in better", "About Chikkamagaluru district."],
  ["cmujeurcd003z04jx6jta3g97", "mysuru", "Countdown begins for shifting Mangaluru from SR to SWR", "About Mangaluru (Dakshina Kannada)."],
  ["cmtjoto0s000504l4i1is6h1i", "bengaluru-urban", "Lokayukta finds fault with Bengaluru South district", "Bengaluru South district is Ramanagara, not Bengaluru Urban."],
  ["cmtl4aoxd000b04kzguiatyx6", "bengaluru-urban", "13 from Karnataka still untraced in Nepal", "Karnataka-wide; no Bengaluru Urban link in the story."],
  ["cmuk23ooa009k2yxngldxfzf0", "mumbai", "4 killed, 5 injured as metal container carrying gelatin sticks", "The blast was in Yavatmal district."],
  ["cmuk1taqm005g2yxna8ne5p8k", "hyderabad", "Bhadragiri Mart, a tribal women-led enterprise", "About Bhadradri Kothagudem district."],
];
for (const [id, district, title, why] of OTHER_PLACE) {
  FIXES.push({
    table: "NewsItem", id, op: "delete", kind: "delete", was: { title },
    label: `${district}: "${title}"`,
    why: `${why} Saved by the old job without a place check; the job and /api/data/news now check the place (src/lib/news-quality.ts).`,
    source: `http://localhost:3000/api/data/news?district=${district} (verifier, ${CHECKED})`,
  });
}

// ── NewsItem: advertorials and price pages (#18) ─────────────────────────
const PROMOTIONS: Array<[string, string, string]> = [
  ["cmuk1dv8j000t2yxndumm76mg", "chennai", "Aarthi Scans & Labs Ranked #1 in Diagnostics"],
  ["cmuk1o402003x2yxn8h0wzo8w", "bengaluru-urban", "Karnataka CM inaugurates Eugenix hair restoration center"],
  ["cmuk1z5a100892yxnrmgfw66r", "mumbai", "Kalpataru Among the First Real Estate Companies"],
  ["cmuk1yi49007r2yxn3zql8yxq", "lucknow", "Gold Rate Today in Lucknow"],
];
for (const [id, district, title] of PROMOTIONS) {
  FIXES.push({
    table: "NewsItem", id, op: "delete", kind: "delete", was: { title },
    label: `${district}: "${title}"`,
    why: "Advertorial / daily price page, not civic news. The job skips these now (isPromotional, src/lib/news-quality.ts).",
    source: `http://localhost:3000/api/data/news?district=${district} (verifier, ${CHECKED})`,
  });
}

// ── NewsItem: one story shown several times (#16) ────────────────────────
// Canonical = the earliest copy still shown (the job's own rule,
// findCanonicalStory). Only clusters the new list rule does not merge by
// itself, plus the verifier's Mandya pair. Each copy: [id, title prefix].
const DUPLICATES: Array<{ district: string; story: string; canonical: string; copies: Array<[string, string]> }> = [
  { district: "mandya", story: "Farmers' Cauvery protest in Mandya, 24 Sep", canonical: "cmugjyskh002z04i4q32izr3k",
    copies: [["cmugjysf8002y04i4t6s3kavh", "Cauvery row: Farmers claim injustice"]] },
  { district: "bengaluru-urban", story: "BWSSB area extended to the whole district", canonical: "cmuhze422000c04jpfoigu5lg",
    copies: [["cmujetziq000b04jxlz4oxrok", "BWSSB limits expanded to entire Bengaluru Urban"], ["cmujetzal000504jxfu5sk63c", "Karnataka Expands BWSSB Mandate"]] },
  { district: "chennai", story: "Tesla experience centre opens in Chennai", canonical: "cmuk1ibx700202yxn8frvxwb8",
    copies: [["cmuk1gug4001i2yxnv29uk25j", "Tesla opens sixth India Experience Centre"], ["cmuk1hwpd001u2yxnvybrdcj8", "Chennai gets new Tesla Experience Center"]] },
  { district: "chennai", story: "Starbucks to set up its GCC in Chennai", canonical: "cmuc9mz98001t04jmyw2m0jpx",
    copies: [
      ["cmuc9mwyu000h04jmvieexz8x", "Starbucks to set up Global Capability Centre in Chennai, create 800 jobs"],
      ["cmuc9mwp7000b04jmr56b3xds", "Starbucks signs MOU with TN Government"],
      ["cmuf4ilph000t04l6ehjsydqz", "Starbucks Signs MoU With TN Govt"],
      ["cmuc9mycf001b04jm18g9ufge", "Starbucks to set up GCC in Chennai, hiring"],
      ["cmuc9my2j001504jmhfhby9j0", "Starbucks to build India technology hub"],
      ["cmudp2pt4000b04l8sy8av5nq", "Starbucks opening tech hub in Chennai"],
      ["cmuc9mxra000z04jm6lic9wtw", "Coffee Major Starbucks to Set Shop"],
      ["cmuc9mxho000t04jm4j12ru43", "Starbucks to set up India GCC in Chennai"],
      ["cmugjyegd000o04i4v95nyosm", "Starbucks Inks MoU with Tamil Nadu Government"],
    ] },
  { district: "kolkata", story: "23 police officers transferred in West Bengal, 26 Sep", canonical: "cmuk1yfdz007g2yxnn2z91w47",
    copies: [
      ["cmuk1utd7005x2yxn964tk797", "In major reshuffle, 23 police officers"],
      ["cmuk1xlaq006t2yxnpumx7pma", "WB: 23 Top Cops Shifted"],
      ["cmuk1yexf007d2yxnmdzrl6x4", "In high-level reshuffle, 23 police officers"],
      ["cmuk1tl7e005n2yxnc7gyhrso", "West Bengal govt reshuffles 23 senior police officers"],
      ["cmuk1yern007c2yxnjymcblc5", "West Bengal Govt Transfers 23 IPS Officers"],
      ["cmuk1vqkw006b2yxne6cyv8ic", "23 IPS transferred in a latest rejig"],
      ["cmuk1vlxc00692yxntuff9cxh", "WB govt transfers 17 IPS, 6 WBPS officers"],
    ] },
  { district: "kolkata", story: "Second attack on Kunal Ghosh, 27 Sep", canonical: "cmuk1wtxs006l2yxnvh7tnnkv",
    copies: [["cmuk1u4lq005q2yxnfhg3ndi7", "'They wanted to kill me': TMC MLA"], ["cmuk1x530006o2yxneo9dz53f", "‘Today, they wanted to kill me’"]] },
  { district: "mumbai", story: "Maharashtra declares drought in 265 talukas", canonical: "cmuk21sx1008u2yxn993uv8ph",
    copies: [
      ["cmuk222xf00912yxn8es40cw9", "Maharashtra declares drought in 265 talukas amidst"],
      ["cmuk23o3q009h2yxn9kqjr2us", "Maharashtra Government declares drought in 265 talukas"],
      ["cmuk21ive008r2yxnx6ukb66e", "Drought declared in three-quarters"],
    ] },
  { district: "mysuru", story: "Mysuru Kambala on 18–19 October", canonical: "cmuhzexv9004f04jpr88tbivi",
    copies: [
      ["cmuhzeyr8004y04jpwi0f1il6", "Mysuru Kambala: 150–160 buffalo pairs"],
      ["cmuhzf1kq005o04jpe1vfk8u3", "Kambala will be held as part of Mysuru Dasara"],
      ["cmuhzeyls004x04jp2cznyx95", "160 pairs of buffaloes to leave for Mysuru"],
      ["cmuhzey46004l04jpdsqvhpfg", "Kambala in Mysuru on October 18, 19"],
      ["cmujeuqir003t04jx43anihmz", "Mysore Kambala to be held"],
    ] },
  { district: "mysuru", story: "Gavimath seer to inaugurate Mysuru Dasara", canonical: "cmugjz1zk004s04i4p3wx6vn1",
    copies: [
      ["cmugjz1q0004m04i4r7so6tsn", "Gavisiddeshwara Mahaswamiji To Inaugurate"],
      ["cmugjz0yz004904i4sqg1zdtg", "Gavimutt seer to inaugurate Dasara"],
      ["cmugjz1fy004g04i4ta1a34xj", "Gavimath seer to inaugurate Mysuru Dasara"],
      ["cmugjz2ko005404i4vfppzvv0", "Gavimath pontiff to inaugurate Mysuru Dasara"],
    ] },
  { district: "pune", story: "Bar operator shot dead in Shirur", canonical: "cmu9es8ps006s04iiozktn21l",
    copies: [["cmu9es8gy006m04ii8hryowyb", "Beer bar operator shot dead in Pune’s Shirur"]] },
  { district: "pune", story: "₹180 crore for Pune Metro expansion", canonical: "cmudp3sgh005w04l8szdnrq4h",
    copies: [["cmuhzfapz006w04jpefccb8pm", "Maharashtra Approves Rs. 1.8 bn for Pune Metro"]] },
  { district: "pune", story: "Pune liquor ban for Ganeshotsav withdrawn", canonical: "cmtxz9aet007r04jmmdo8ysf8",
    copies: [
      ["cmtxz9czw008h04jm8f1shm7j", "After Bombay High Court Rap, Pune Collector Withdraws"],
      ["cmtxz9ayo008404jmfofdpmi5", "Pune admin revokes 10-day liquor ban"],
      ["cmtxz9aly007x04jm28qz97hy", "13-day liquor sale ban during Ganeshotsav withdrawn"],
      ["cmtxz9csf008b04jmb6mm6bb6", "After HC rebuke, govt recalls Pune liquor ban"],
    ] },
];
for (const c of DUPLICATES) {
  for (const [id, title] of c.copies) {
    FIXES.push({
      table: "NewsItem", id, op: "update", kind: "update",
      set: { duplicateOf: c.canonical }, was: { duplicateOf: null, title },
      label: `${c.district}: "${title}" → copy of ${c.canonical}`,
      why: `Same story (${c.story}) from another outlet; the list shows one card per story. The dedupe rule was loosened too (src/lib/news-dedupe.ts).`,
      source: `http://localhost:3000/api/data/news?district=${c.district} (verifier, ${CHECKED})`,
    });
  }
}

// ── NewsItem: topic and page tag from the old substring classifier (#15) ─
// New values = today's classifier (src/lib/news-keywords.ts) on the same
// headline. (A Kambala copy tagged "rti" is marked a duplicate above instead.)
const RETAG: Array<[string, string, string, [string, string], [string, string]]> = [
  // [id, district, title prefix, [category was, now], [targetModule was, now]]
  ["cmudp39hp003r04l8y8j1r59i", "mandya", "Mandya: Man sleeping in auto-rickshaw brutally murdered", ["crime", "crime"], ["transport", "police"]],
  ["cmudp39n8003s04l8xncbsz7g", "mandya", "India News | Karnataka: Lokayukta Raids in Mandya, Kalaburagi", ["general", "general"], ["crops", "news"]],
  ["cmuf4j1oq004004l6m0yp9rri", "mandya", "Karnataka: Lokayukta raids in Mandya, Kalaburagi", ["general", "general"], ["crops", "news"]],
  ["cmtv4d89y005a04larj75je6f", "mandya", "Students demonstrate scientific temper", ["politics", "education"], ["leaders", "education"]],
  ["cmudp3qmk005u04l87ejbf72b", "pune", "Heavy rain lashes Pune after dry stretch", ["politics", "weather"], ["leaders", "weather"]],
  ["cmujeuxvt004k04jx0wa5ozhj", "pune", "Pune wins historic bid to host UCI Road World Championships", ["politics", "general"], ["leaders", "news"]],
  ["cmujeulnf002704jx51tr50f5", "mumbai", "Temple trip turns tragic", ["politics", "general"], ["leaders", "news"]],
  ["cmujeulsw002804jxdp0ucgx4", "mumbai", "MMR overtakes NCR as India’s biggest housing market", ["agriculture", "general"], ["housing", "housing"]],
  ["cmuk1pcw2004h2yxn2i4j1wp6", "hyderabad", "Hyderabad man loses Rs 3.73 crore in fake investment scheme", ["development", "crime"], ["budget", "police"]],
  ["cmuk1p7sx004e2yxnc9t1muoe", "hyderabad", "Hyderabad mega job mela", ["general", "general"], ["elections", "news"]],
  ["cmuhzf1c9005i04jpy3w91rj9", "mysuru", "VVCE’s first batch to reunite", ["crime", "education"], ["police", "education"]],
  ["cmuhzexv9004f04jpr88tbivi", "mysuru", "Mysuru Kambala: 150-160 selected buffalo pairs", ["general", "general"], ["leaders", "news"]],
  ["cmugjz3cn005i04i4nvhpzh3q", "mysuru", "University of Mysore: Rs 150 crore irregularities", ["education", "education"], ["budget", "education"]],
  ["cmuk1mz1q003m2yxnqb4jddef", "bengaluru-urban", "Youth dies by suicide at relative’s house", ["general", "general"], ["housing", "news"]],
  ["cmuc9n7wz002x04jm8bq2asfh", "lucknow", "Lucknow court awards 10 years’ imprisonment", ["politics", "general"], ["leaders", "courts"]],
  ["cmugjz9fn006e04i4vil1eeyw", "new-delhi", "Child Sexual Abuse Cases Can't Be Settled", ["general", "general"], ["transport", "courts"]],
];
for (const [id, district, title, [catWas, catNow], [modWas, modNow]] of RETAG) {
  const set: Record<string, Value> = {};
  const was: Record<string, Value> = { title };
  if (catWas !== catNow) { set.category = catNow; was.category = catWas; }
  if (modWas !== modNow) { set.targetModule = modNow; was.targetModule = modWas; }
  if (Object.keys(set).length === 0) continue;
  FIXES.push({
    table: "NewsItem", id, op: "update", kind: "update", set, was,
    label: `${district}: "${title}"`,
    why: "Tagged by the old substring classifier ('mp' in 'temper', 'ragi' in 'Kalaburagi', 'auto' before 'murdered'); today's whole-word classifier gives the new tags.",
    source: `http://localhost:3000/api/data/news?district=${district} (verifier, ${CHECKED})`,
  });
}

// ── BudgetEntry: hand-seeded district "budgets" (#8) ─────────────────────
const BUDGET_WHY: Record<string, string> = {
  "new-delhi": "Delhi Government department heads credited to New Delhi district; they add up to exactly Mumbai's ₹65,200 crore; 'spent' ~66 % of every line.",
  mumbai: "Seeded 'BMC Budget 2025-26' + 'MMRDA / State Allocation' rows sum to ₹65,200 crore; BMC's own 2025-26 estimate is ₹74,427.41 crore, and 'spent' was a fixed share.",
  lucknow: "Uttar Pradesh state department heads credited to Lucknow district (sum ₹61,000 crore), spent 0.",
  "bengaluru-urban": "BBMP + BDA + BMRCL + state heads summed as one district budget; 'spent' is exactly 44 % (2025-26) / ~70 % (2024-25) of every line.",
  hyderabad: "Telangana state heads and GHMC figures with 'spent' labelled 'estimated from state avg utilisation'.",
};
const BUDGET_SOURCE: Record<string, string> = {
  "new-delhi": "http://localhost:3000/api/data/glance?district=new-delhi&state=delhi (verifier: allocated 652000000000, same as Mumbai)",
  mumbai: "https://www.tribuneindia.com/news/bmc/bmc-proposes-rs-74427-41-crore-budget-for-2025-26-up-14-19-from-last-year",
  lucknow: "http://localhost:3000/en/uttar-pradesh/lucknow (verifier: UP state heads summing to 61,000 crore)",
  "bengaluru-urban": "read-only BudgetEntry query 2026-09-28: spent/allocated 0.439–0.442 (2025-26), ~0.70 (2024-25) on every row",
  hyderabad: "read-only BudgetEntry query 2026-09-28: source 'estimated from state avg utilisation'",
};
const SEEDED_BUDGET: Array<[string, string, string, string, number]> = [
  // [id, district, fiscalYear, sector, allocated (rupees)]
  ["cmnakaty7001g1axn3xmrkpvn", "bengaluru-urban", "2024-25", "BBMP — Education (Schools)", 4200000000],
  ["cmnakatwt001f1axnvqu0vyuq", "bengaluru-urban", "2024-25", "BBMP — Public Health & Hospitals", 6800000000],
  ["cmnakatty001d1axn8r4f96bn", "bengaluru-urban", "2024-25", "BBMP — Roads & Infrastructure", 32000000000],
  ["cmnakatvg001e1axn2o2fyjlc", "bengaluru-urban", "2024-25", "BBMP — Solid Waste Management", 8500000000],
  ["cmnakau4l001i1axn3fqrvn1i", "bengaluru-urban", "2024-25", "BDA — Housing Projects", 8000000000],
  ["cmnakatzu001h1axn2agcz432", "bengaluru-urban", "2024-25", "BDA — Layout Development", 12000000000],
  ["cmnakaua8001m1axnqqd6ick2", "bengaluru-urban", "2024-25", "BESCOM — Power Infrastructure", 22000000000],
  ["cmnakaubj001n1axn2rzzlhdv", "bengaluru-urban", "2024-25", "BMTC — Transport", 6500000000],
  ["cmnakau8w001l1axniihhy6mo", "bengaluru-urban", "2024-25", "BWSSB — Sewerage (STP)", 9500000000],
  ["cmnakau7k001k1axnd5dtt7q0", "bengaluru-urban", "2024-25", "BWSSB — Water Supply", 18000000000],
  ["cmnakaufy001q1axnpqjufvj8", "bengaluru-urban", "2024-25", "Education (Primary — State)", 5800000000],
  ["cmnakauho001r1axn34xrrm9b", "bengaluru-urban", "2024-25", "Health (State — PHC/CHC)", 3900000000],
  ["cmnakauj1001s1axne22mujvs", "bengaluru-urban", "2024-25", "Industries & IT Parks", 2800000000],
  ["cmnakauem001p1axn7ac6wndz", "bengaluru-urban", "2024-25", "Lake Rejuvenation (BBMP)", 3200000000],
  ["cmnakau66001j1axns7e1lwqs", "bengaluru-urban", "2024-25", "Namma Metro (BMRCL)", 45000000000],
  ["cmnakauns001v1axn2aye1q5f", "bengaluru-urban", "2024-25", "Police & Law Enforcement", 4500000000],
  ["cmnakaulq001u1axnsyz4hwxh", "bengaluru-urban", "2024-25", "Revenue & Registration", 850000000],
  ["cmnakaud9001o1axnighvvz3r", "bengaluru-urban", "2024-25", "Smart City Bengaluru", 5000000000],
  ["cmnakaukd001t1axnwtnjc3x6", "bengaluru-urban", "2024-25", "Social Welfare", 2200000000],
  ["cmnakaut5001z1axnhkj9w6yn", "bengaluru-urban", "2025-26", "BBMP — Education (Schools)", 4600000000],
  ["cmnakaurv001y1axnviw3ftnv", "bengaluru-urban", "2025-26", "BBMP — Public Health & Hospitals", 7400000000],
  ["cmnakaup5001w1axnav09irzv", "bengaluru-urban", "2025-26", "BBMP — Roads & Infrastructure", 35000000000],
  ["cmnakauqi001x1axn28pe8y41", "bengaluru-urban", "2025-26", "BBMP — Solid Waste Management", 9200000000],
  ["cmnakaux400211axn65ydms44", "bengaluru-urban", "2025-26", "BDA — Housing Projects", 8800000000],
  ["cmnakauvs00201axnhps1durp", "bengaluru-urban", "2025-26", "BDA — Layout Development", 13500000000],
  ["cmnakav3j00251axn29s2bvfb", "bengaluru-urban", "2025-26", "BESCOM — Power Infrastructure", 24000000000],
  ["cmnakav4v00261axn3bzgm2is", "bengaluru-urban", "2025-26", "BMTC — Transport", 7200000000],
  ["cmnakav2700241axnva0kplhh", "bengaluru-urban", "2025-26", "BWSSB — Sewerage (STP)", 10500000000],
  ["cmnakav0u00231axnk239atij", "bengaluru-urban", "2025-26", "BWSSB — Water Supply", 20000000000],
  ["cmnakav9000291axnocq52o7z", "bengaluru-urban", "2025-26", "Education (Primary — State)", 6400000000],
  ["cmnakavac002a1axnz7r4fbxg", "bengaluru-urban", "2025-26", "Health (State — PHC/CHC)", 4300000000],
  ["cmnakavbp002b1axnlbdacxpl", "bengaluru-urban", "2025-26", "Industries & IT Parks", 3100000000],
  ["cmnakav7l00281axn3uhz8614", "bengaluru-urban", "2025-26", "Lake Rejuvenation (BBMP)", 3800000000],
  ["cmnakauyg00221axn3vd8hzqk", "bengaluru-urban", "2025-26", "Namma Metro (BMRCL)", 52000000000],
  ["cmnakavfo002e1axncg1vi6z0", "bengaluru-urban", "2025-26", "Police & Law Enforcement", 5000000000],
  ["cmnakavec002d1axn45m2i715", "bengaluru-urban", "2025-26", "Revenue & Registration", 950000000],
  ["cmnakav6800271axnmpo8bxwj", "bengaluru-urban", "2025-26", "Smart City Bengaluru", 5500000000],
  ["cmnakavd2002c1axngkcfh66n", "bengaluru-urban", "2025-26", "Social Welfare", 2450000000],
  ["cmnrsybv6000syaxnahv5m9qo", "hyderabad", "2025-26", "GHMC — Infrastructure", 30000000000],
  ["cmnrsybv6000uyaxnyxvud4w7", "hyderabad", "2025-26", "GHMC — Roads", 25000000000],
  ["cmnrsybv6000tyaxn0gbx9z6e", "hyderabad", "2025-26", "GHMC — Solid Waste Management", 15000000000],
  ["cmnrsybv6000myaxnpwszydzd", "hyderabad", "2026-27", "Education", 180000000000],
  ["cmnrsybv6000nyaxnlasciiuj", "hyderabad", "2026-27", "Health & Medical", 120000000000],
  ["cmnrsybv6000oyaxnq9yh4366", "hyderabad", "2026-27", "Hyderabad Metro Rail", 11000000000],
  ["cmnrsybv6000ryaxnjmzxjyy2", "hyderabad", "2026-27", "IT & Communications", 15000000000],
  ["cmnrsybv5000lyaxn78qkvfi4", "hyderabad", "2026-27", "Municipal Admin & Urban Development", 179070000000],
  ["cmnrsybv6000qyaxn461hi5ut", "hyderabad", "2026-27", "Police & Home Affairs", 100000000000],
  ["cmnrsybv6000pyaxn1sr436lj", "hyderabad", "2026-27", "Roads & Buildings", 80000000000],
  ["cmntdqt8l000llnxndppqz7ki", "lucknow", "2025-26", "Agriculture", 25000000000],
  ["cmntdqt8j000elnxnurynlaqt", "lucknow", "2025-26", "Education", 150000000000],
  ["cmntdqt8l000flnxnni47v78e", "lucknow", "2025-26", "Health & Medical", 95000000000],
  ["cmntdqt8l000nlnxnvw1e1ja0", "lucknow", "2025-26", "Lucknow Metro (LMRC)", 20000000000],
  ["cmntdqt8l000ilnxnk2qww1yh", "lucknow", "2025-26", "Municipal Administration (LMC)", 55000000000],
  ["cmntdqt8l000glnxn6fxp9qp5", "lucknow", "2025-26", "Police & Home Affairs", 85000000000],
  ["cmntdqt8l000hlnxn3jyz4zrt", "lucknow", "2025-26", "Roads & PWD", 70000000000],
  ["cmntdqt8l000mlnxnphhlupih", "lucknow", "2025-26", "Social Welfare", 35000000000],
  ["cmntdqt8l000jlnxn8cckwge2", "lucknow", "2025-26", "Urban Development (LDA)", 45000000000],
  ["cmntdqt8l000klnxnvcwxdun2", "lucknow", "2025-26", "Water Supply (Jal Kal)", 30000000000],
  ["cmnfm3fl9001e3rxn1bf3ohit", "mumbai", "2025-26", "Development Planning", 80000000000],
  ["cmnfm3fl9001a3rxnrk0ntyyc", "mumbai", "2025-26", "Education", 40000000000],
  ["cmnfm3fl9001c3rxn1k7khqg8", "mumbai", "2025-26", "Fire Brigade", 12000000000],
  ["cmnfm3fl9001d3rxnoxxktzl2", "mumbai", "2025-26", "Gardens & Open Spaces", 10000000000],
  ["cmnfm3fl900193rxnpjimni48", "mumbai", "2025-26", "Health & Hospitals", 55000000000],
  ["cmnfm3fl700163rxnmmvnxi0y", "mumbai", "2025-26", "Infrastructure & Roads", 150000000000],
  ["cmnfm3fl9001f3rxnb7z8qu0o", "mumbai", "2025-26", "Metro & Transport (MMRDA)", 120000000000],
  ["cmnfm3fl900183rxnxr5fl9xw", "mumbai", "2025-26", "Sewerage & Drainage", 65000000000],
  ["cmnfm3fl9001b3rxn49hqwz82", "mumbai", "2025-26", "Solid Waste Management", 35000000000],
  ["cmnfm3fl900173rxnmogxffat", "mumbai", "2025-26", "Water Supply", 85000000000],
  ["cmnf0n51k000m1dxnm5erdd86", "new-delhi", "2025-26", "Education", 160000000000],
  ["cmnf0n51l000x1dxnt9tezzmy", "new-delhi", "2025-26", "Environment & Forest", 12000000000],
  ["cmnf0n51l000n1dxns8os06p7", "new-delhi", "2025-26", "Health & Hospitals", 90000000000],
  ["cmnf0n51l000v1dxnorlqla76", "new-delhi", "2025-26", "Housing", 25000000000],
  ["cmnf0n51l000p1dxn4fsck8yj", "new-delhi", "2025-26", "Police & Home (Central)", 85000000000],
  ["cmnf0n51l000t1dxnkq2pp1gq", "new-delhi", "2025-26", "Power Subsidy", 30000000000],
  ["cmnf0n51l000u1dxnk182ndfw", "new-delhi", "2025-26", "Public Works", 30000000000],
  ["cmnf0n51l000w1dxnbjk0ea5k", "new-delhi", "2025-26", "Revenue & General Admin", 15000000000],
  ["cmnf0n51l000s1dxnnxumauo4", "new-delhi", "2025-26", "Social Welfare", 35000000000],
  ["cmnf0n51l000o1dxnqnoks7jp", "new-delhi", "2025-26", "Transport (DMRC+DTC+Roads)", 80000000000],
  ["cmnf0n51l000r1dxnpw79m1q9", "new-delhi", "2025-26", "Urban Development", 40000000000],
  ["cmnf0n51l000q1dxn1lifxg8u", "new-delhi", "2025-26", "Water & Sewerage (DJB)", 50000000000],
];
for (const [id, district, fy, sector, allocated] of SEEDED_BUDGET) {
  FIXES.push({
    table: "BudgetEntry", id, op: "delete", kind: "delete", was: { sector, fiscalYear: fy, allocated },
    label: `${district} FY ${fy}: ${sector} (₹${Math.round(allocated / 1e7).toLocaleString("en-IN")} crore)`,
    why: `${BUDGET_WHY[district]} Hidden already by NOT_SEEDED_BUDGET (src/lib/data-filters.ts).`,
    source: BUDGET_SOURCE[district],
  });
}

// ── GovernmentExam: invented dates and posts on April seed rows (#10, #11) ─
const EXAM_HIDE: Array<[string, string, string, string, number, string]> = [
  // [id, title, examDate was (as Prisma reads the stored timestamp), who, vacancies was, source]
  ["cmnfml9wp000uk0xn8el6vedd", "Maharashtra Talathi Recruitment 2026", "2026-10-15T00:00:00.000Z", "Mumbai, Pune", 4710,
    "https://testbook.com/news/maharashtra-talathi-bharti-2026-out/ (1,539 posts; exam 25 Oct 2026 — not an official notice, so the fields are cleared, not rewritten)"],
  ["cmnfmla6c001ck0xnxd00x6i8", "TN Police SI (Sub-Inspector of Police) Recruitment 2026", "2026-10-15T00:00:00.000Z", "Chennai", 969,
    "https://www.adda247.com/exams/tn/tnusrb-si/ (TNUSRB SI 2026 notification not out; no exam date)"],
  ["cmnfmla1m0012k0xnzoscn91l", "WB Police Constable Recruitment 2026", "2026-10-01T00:00:00.000Z", "Kolkata", 8632,
    "https://www.adda247.com/jobs/wb-police-constable-recruitment/ (last cycle: exam 29 Jan 2026, 11,749 posts; no 1 Oct 2026 exam)"],
];
for (const [id, title, examDate, who, vacancies, source] of EXAM_HIDE) {
  FIXES.push({
    table: "GovernmentExam", id, op: "update", kind: "hide",
    set: { examDate: null, vacancies: null }, was: { title, examDate, vacancies },
    label: `${title} (shown as "Next exam" in ${who})`,
    why: "April seed row (status UNVERIFIED, needsVerification, no source): the date and post count match no notification. The overview now shows only checked exam dates (src/lib/next-exam.ts).",
    source,
  });
}

// ── InfraProject: a 2008 memorial shown as "Announced" (#3) ──────────────
FIXES.push({
  table: "InfraProject", id: "cmnt22lcm002910qjhkxg5m3u", op: "delete", kind: "delete",
  was: { name: "Ambedkar Memorial, Lucknow", status: "Announced" },
  label: 'lucknow: "Ambedkar Memorial, Lucknow" — Announced, 0 %',
  why: "Made from a news link with no description; the Ambedkar Memorial Park opened in 2008, so an 'Announced' project row is unfounded.",
  source: "https://en.wikipedia.org/wiki/Ambedkar_Memorial_Park",
});

// ── District.talukCount and Taluk name (#6, #7) ──────────────────────────
const TALUK_COUNTS: Array<[string, string, number, number | null, string]> = [
  // [District id, slug, was, now, source]
  ["cmmvn6wsa00j4muxn0644c207", "mysuru", 7, 9, "https://mysore.nic.in/en/subdivision-blocks/ (table lists 9 taluks)"],
  ["cmnsx65is001w5vxngq0z9ujl", "lucknow", 4, 5, "https://lucknow.nic.in/tehsil/ ('There are five tehsils in Lucknow')"],
  ["cmnfhephn000ql6xnlzvegajf", "pune", 14, 16, "https://pune.gov.in/about-district/ ('Tahsils : 16')"],
  ["cmnfheqze0016l6xncib8jxq4", "chennai", 4, null, "https://chennai.nic.in/about-district/administrative-setup/revenue-administration/ (16 revenue taluks listed, summary says 17; our 4 were invented)"],
  ["cmnfhentm000hl6xntaak7dxo", "mumbai", 5, null, "https://mumbaisuburban.gov.in/about-district/ (Mumbai Suburban: 3 talukas; our 5 zones were invented)"],
  ["cmnfheppj000vl6xn5v7abegx", "kolkata", 4, null, "https://en.wikipedia.org/wiki/Kolkata_district (no subdivisions or blocks)"],
  ["cmnf0i70h0005xlxn23f7ddt5", "new-delhi", 3, null, "https://dmnewdelhi.delhi.gov.in/tehsil/ (says three tehsils, names New Delhi and Delhi Cantt)"],
];
for (const [id, slug, was, now, source] of TALUK_COUNTS) {
  FIXES.push({
    table: "District", id, op: "update", kind: now === null ? "hide" : "update",
    set: { talukCount: now }, was: { slug, talukCount: was },
    label: `${slug}: talukCount`,
    why: now === null ? "Our sub-district units were invented; no verified count to show." : "The district portal's own count.",
    source,
  });
}
FIXES.push({
  table: "Taluk", id: "cmnsx65ka001x5vxnl7rxphzt", op: "update", kind: "update",
  set: { name: "Lucknow Sadar", nameLocal: "लखनऊ सदर" }, was: { slug: "lucknow-city", name: "Lucknow City", nameLocal: "लखनऊ शहर" },
  label: "lucknow: taluk lucknow-city",
  why: "The tehsil is Sadar on the district portal.",
  source: "https://lucknow.nic.in/tehsil/",
});

// ═════════════════════════════════════════════════════════════════════════
const delegateName = (table: string) => table[0].toLowerCase() + table.slice(1);

function show(v: unknown): string {
  if (v === null || v === undefined) return "null";
  if (v instanceof Date) return v.toISOString();
  if (typeof v === "string") return JSON.stringify(v.length > 70 ? v.slice(0, 67) + "…" : v);
  return String(v);
}

/** Stored value vs expected: dates by ISO time, numbers within 1e-6, a title by its checked prefix. */
function same(field: string, current: unknown, expected: Value): boolean {
  if (current === null || current === undefined) return expected === null;
  if (expected === null) return false;
  if (current instanceof Date) return typeof expected === "string" && current.getTime() === new Date(expected).getTime();
  if (typeof expected === "number") return Math.abs(Number(current) - expected) < 1e-6;
  if (field === "title") return String(current).startsWith(String(expected));
  return String(current) === String(expected);
}

function toDb(field: string, v: Value): unknown {
  if (field === "examDate" && typeof v === "string") return new Date(v);
  return v;
}

async function main() {
  const seen = new Set<string>();
  for (const f of FIXES) {
    const key = `${f.table}:${f.id}`;
    if (seen.has(key)) throw new Error(`Duplicate fix for ${key}`);
    seen.add(key);
  }

  const p = new PrismaClient({ adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL! }) });
  type Planned = { fix: Fix; data?: Record<string, unknown> };
  const plan: Planned[] = [];
  const counts: Record<string, Record<string, number>> = {};
  const tally = (t: string, k: string) => {
    counts[t] ??= { update: 0, hide: 0, delete: 0, "already done": 0, "not found": 0, "changed since check": 0 };
    counts[t][k]++;
  };

  try {
    let current = "";
    for (const f of FIXES) {
      if (f.table !== current) {
        current = f.table;
        console.log(`\n══ ${f.table} ══`);
      }
      const rows = (await p.$queryRawUnsafe(`SELECT * FROM "${f.table}" WHERE id = $1`, f.id)) as Array<Record<string, unknown>>;
      const row = rows[0];
      console.log(`\n• ${f.kind.toUpperCase()} ${f.table} ${f.id} — ${f.label}`);
      console.log(`  why:    ${f.why}`);
      console.log(`  source: ${f.source}`);
      if (!row) {
        console.log("  → row not found (already removed?) — skipped");
        tally(f.table, "not found");
        continue;
      }
      // Changed since the check? (applies to deletes and updates alike)
      const drift = Object.entries(f.was).filter(([field, expected]) => {
        if (!(field in row)) throw new Error(`${f.table}.${field} does not exist (fix ${f.id})`);
        const planned = f.set?.[field];
        const done = f.set && field in f.set && same(field, row[field], planned as Value);
        return !same(field, row[field], expected) && !done;
      });
      if (drift.length > 0) {
        for (const [field, expected] of drift) {
          console.log(`    ${field}: now ${show(row[field])}, was ${show(expected)} on ${CHECKED} — CHANGED SINCE CHECK`);
        }
        console.log("  → skipped; review by hand");
        tally(f.table, "changed since check");
        continue;
      }
      if (f.op === "delete") {
        console.log(`  → delete row`);
        plan.push({ fix: f });
        tally(f.table, "delete");
        continue;
      }
      const data: Record<string, unknown> = {};
      for (const [field, planned] of Object.entries(f.set!)) {
        if (same(field, row[field], planned)) {
          console.log(`    ${field}: ${show(row[field])} (already ${show(planned)})`);
          continue;
        }
        console.log(`    ${field}: ${show(row[field])} → ${show(planned)}`);
        data[field] = toDb(field, planned);
      }
      if (Object.keys(data).length === 0) {
        console.log("  → already applied — skipped");
        tally(f.table, "already done");
        continue;
      }
      plan.push({ fix: f, data });
      tally(f.table, f.kind === "hide" ? "hide" : "update");
    }

    console.log("\n══ Summary ══");
    for (const [t, c] of Object.entries(counts)) {
      console.log(`${t.padEnd(15)} ${Object.entries(c).map(([k, n]) => `${k} ${n}`).join("   ")}`);
    }
    const n = (k: Fix["kind"]) => plan.filter((x) => x.fix.kind === k).length;
    console.log(`Total changes to apply: ${plan.length} (updates ${n("update")}, hides ${n("hide")}, deletes ${n("delete")})`);

    if (!CONFIRM) {
      console.log("\nDry run only. Re-run with --confirm to apply (one transaction).");
      return;
    }
    if (plan.length === 0) {
      console.log("Nothing to do.");
      return;
    }
    type Delegate = {
      update: (a: unknown) => Promise<unknown>;
      deleteMany: (a: unknown) => Promise<{ count: number }>;
    };
    const deletes = new Map<string, string[]>();
    for (const { fix } of plan) if (fix.op === "delete") deletes.set(fix.table, [...(deletes.get(fix.table) ?? []), fix.id]);
    await p.$transaction(
      async (tx) => {
        const model = (table: string) => (tx as unknown as Record<string, Delegate>)[delegateName(table)];
        for (const { fix, data } of plan) {
          if (fix.op === "update") await model(fix.table).update({ where: { id: fix.id }, data });
        }
        for (const [table, ids] of deletes) {
          const { count } = await model(table).deleteMany({ where: { id: { in: ids } } });
          if (count !== ids.length) throw new Error(`${table}: expected to delete ${ids.length} rows, deleted ${count} — rolled back`);
        }
      },
      { timeout: 600_000, maxWait: 30_000 },
    );
    console.log(`\nDone: applied ${plan.length} changes in one transaction.`);
    console.log("Clear the Redis caches (admin → Cache) so pages pick this up at once.");
  } finally {
    await p.$disconnect();
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
