/**
 * ForThePeople.in — Your District. Your Data. Your Right.
 * © 2026 Jayanth M B. MIT License.
 * https://github.com/jayanthmb14/forthepeople
 */

// ═══════════════════════════════════════════════════════════════════════
//  Alerts & warnings — "Is there a warning I should act on, and what do I
//  do?"  (docs/LAYOUT.md recipe)
// ═══════════════════════════════════════════════════════════════════════
//
//  The answer: "3 warnings are active for Mandya. Red (act now): 1.
//  Orange (be ready): 1."
//
//  Order: PageHeader → Explainer → 4 tiles → the picture (one coloured
//  circle per warning, and what each colour means) → one colour-coded card
//  per warning, most serious first. Tapping a card opens a DetailSheet in
//  that colour: what the colour means, the full notice, where and when,
//  who reported it, WHAT TO DO (plain steps for that kind of warning) and
//  tap-to-call emergency numbers → kinds of warning (ring) → AI insight →
//  news → Share. With no warning the page says so and still shows the
//  emergency numbers. The level colour is a plain dot (the words say it
//  too); no emoji. Sources, "report a mistake" and the weather link are
//  left to the layout (verification panel, "See also").
//
//  Colours follow the IMD idea: red = act now, orange = be ready, yellow =
//  stay alert, green = low risk, blue = for your information. Each card is
//  wrapped in that colour's hue class (ftp-hue-*), so no raw colours.
//
//  Honesty: the API sorts severity as text, so the page sorts by rank
//  itself. Warnings whose end date has passed are marked "Ended" and go to
//  the end. Warnings picked up from news reports say so; a source link is
//  shown when there is one. Times use the shared minute clock (useNow), so
//  nothing time-based is drawn on the server. Every word is in page_alerts
//  (en / kn / hi); warning titles, descriptions and places are data and
//  stay as published; kinds of warning get a plain name (types.*).
"use client";

import { use, useState } from "react";
import { useTranslations } from "next-intl";
import { Bell } from "lucide-react";
import ModuleErrorBoundary from "@/components/common/ModuleErrorBoundary";
import AIInsightCard from "@/components/common/AIInsightCard";
import ModuleNews from "@/components/district/ModuleNews";
import { useAlerts } from "@/hooks/useRealtimeData";
import type { LocalAlert } from "@/hooks/useRealtimeData";
import { useDistrictName, useFormat, useModuleText } from "@/i18n/client";
import { Card, EmptyState, ErrorBlock, LoadingShell, ModulePage, PageHeader, Section, StatStrip, StatTile } from "@/components/district/ui";
import { ChartCard, Explainer } from "@/components/district/visuals";
import { DetailList, DetailSheet } from "@/components/district/DetailSheet";
import { HueDonut, MUTED_SHADE, type DonutSegment } from "@/components/district/daily-services/HueCharts";
import { ActionLink, Chip, SheetBlock, SheetNote, SheetSmall, dataLang, extUrl, hostOf, useNow } from "@/components/services-2/kit";
import { TapCard } from "@/components/services-1/kit";
import { PageActions } from "@/components/district/page-kit";

/** The API sends every column; the shared type leaves a few out. */
type AlertRow = LocalAlert & { descriptionLocal?: string | null; sourceUrl?: string | null; autoGenerated?: boolean | null; updatedAt?: string | null };

type Level = "critical" | "high" | "medium" | "low" | "info" | "other";

const LEVEL_RANK: Record<Level, number> = { critical: 0, high: 1, medium: 2, low: 3, info: 4, other: 5 };
/** Hue class per level, so cards and sheets take that colour. */
const LEVEL_HUE: Record<Level, string> = {
  critical: "ftp-hue-rose",
  high: "ftp-hue-orange",
  medium: "ftp-hue-yellow",
  low: "ftp-hue-green",
  info: "ftp-hue-sky",
  other: "ftp-hue-slate",
};
const LEGEND: Level[] = ["critical", "high", "medium", "low", "info"];

/** How many kinds the ring names before "Other kinds". */
const TOP_KINDS = 5;
/** How many circles the picture draws before "+N more". */
const MAX_SYMBOLS = 20;

const bold = (c: React.ReactNode) => <strong>{c}</strong>;

/** A round dot in the level's colour (the colour is the data; the words say it too). */
function LevelDot({ level, size = 10 }: { level: Level; size?: number }) {
  return (
    <span className={LEVEL_HUE[level]} aria-hidden style={{ display: "inline-flex" }}>
      <span style={{ width: size, height: size, borderRadius: 999, background: "var(--hue)", flexShrink: 0 }} />
    </span>
  );
}

/** One line of a warning card (the notice, the place). `clamp` cuts long text on the card. */
function Meta({ children, lang, clamp }: { children: React.ReactNode; lang?: string; clamp?: number }) {
  const clampStyle: React.CSSProperties = clamp ? { display: "-webkit-box", WebkitLineClamp: clamp, WebkitBoxOrient: "vertical", overflow: "hidden" } : {};
  return (
    <span lang={lang} style={{ display: "block", fontSize: 13, lineHeight: "19px", color: "var(--ftp-text)", overflowWrap: "anywhere", ...clampStyle }}>
      {children}
    </span>
  );
}

function levelOf(severity: string | null | undefined): Level {
  const s = (severity ?? "").trim().toLowerCase();
  return s === "critical" || s === "high" || s === "medium" || s === "low" || s === "info" ? s : "other";
}

/** "water_supply" / "Water Supply" → "water_supply" (the types.* key shape). */
const typeKey = (raw: string) => raw.trim().toLowerCase().replace(/[\s-]+/g, "_");

/** "water_supply" → "Water supply" for kinds with no translation. */
const sentenceCase = (raw: string) => {
  const s = raw.replace(/[_-]+/g, " ").trim().toLowerCase();
  return s.charAt(0).toUpperCase() + s.slice(1);
};

/** Which "what to do" list fits a kind of warning (todo.<group>.*). */
function todoGroup(type: string, title: string): string {
  const s = `${type} ${title}`.toLowerCase();
  if (/flood|cyclone|inundat/.test(s)) return "flood";
  if (/heat/.test(s)) return "heat";
  if (/cold wave|cold/.test(s)) return "cold";
  if (/rain|storm|thunder|lightning|weather/.test(s)) return "storm";
  if (/land ?slide|earth ?quake|natural_disaster|disaster/.test(s)) return "quake";
  if (/fire|emergency|collapse/.test(s)) return "fire";
  if (/water/.test(s)) return "water";
  if (/power|electric/.test(s)) return "power";
  if (/health|disease|outbreak|dengue|malaria|cholera|covid/.test(s)) return "health";
  if (/road|traffic|transport|strike|bandh|shutdown/.test(s)) return "travel";
  return "general";
}

/** Groups where the district disaster help line (1077) is worth showing. */
const DISASTER_GROUPS = new Set(["flood", "storm", "quake", "heat", "cold"]);

function AlertsPageInner({ params }: { params: Promise<{ locale: string; state: string; district: string }> }) {
  const { locale, state, district } = use(params);
  const base = `/${locale}/${state}/${district}`;
  const t = useTranslations("page_alerts");
  const f = useFormat();
  const mt = useModuleText();
  const districtName = useDistrictName(state, district);
  const now = useNow();
  const { data, isLoading, error } = useAlerts(district, state);
  const [openId, setOpenId] = useState<string | null>(null);

  const n = (v: number) => f.number(v);
  const pct = (share: number) => f.number(share, { style: "percent", maximumFractionDigits: 0 });
  const typeLabel = (raw: string) => (t.has(`types.${typeKey(raw)}`) ? t(`types.${typeKey(raw)}`) : sentenceCase(raw));
  const shortDate = (iso: string) => f.date(iso, { day: "numeric", month: "short" });
  const dateTime = (iso: string) => f.date(iso, { day: "numeric", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" });

  /** In force / not started yet / ended, from the dates and the clock (null until the clock is known). */
  const statusOf = (a: AlertRow): "ended" | "upcoming" | "now" | null => {
    if (now <= 0) return null;
    if (a.endDate && new Date(a.endDate).getTime() < now) return "ended";
    if (a.startDate && new Date(a.startDate).getTime() > now) return "upcoming";
    return "now";
  };
  const whenText = (a: AlertRow) =>
    a.startDate ? (a.endDate ? t("list.range", { start: shortDate(a.startDate), end: shortDate(a.endDate) }) : t("list.from", { start: shortDate(a.startDate) })) : null;

  // Most serious first; ended ones last; newest first inside a level.
  const alerts: AlertRow[] = [...((data?.data ?? []) as AlertRow[])].sort((a, b) => {
    const ea = statusOf(a) === "ended" ? 1 : 0;
    const eb = statusOf(b) === "ended" ? 1 : 0;
    return ea - eb || LEVEL_RANK[levelOf(a.severity)] - LEVEL_RANK[levelOf(b.severity)] || (b.createdAt > a.createdAt ? 1 : b.createdAt < a.createdAt ? -1 : 0);
  });
  const live = alerts.filter((a) => statusOf(a) !== "ended");
  const ended = alerts.length - live.length;
  const red = live.filter((a) => levelOf(a.severity) === "critical").length;
  const orange = live.filter((a) => levelOf(a.severity) === "high").length;

  // Warnings per kind, biggest first.
  const byType = Object.entries(
    alerts.reduce((acc: Record<string, number>, a) => {
      acc[a.type] = (acc[a.type] ?? 0) + 1;
      return acc;
    }, {}),
  ).sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]));
  const otherKinds = byType.slice(TOP_KINDS).reduce((s, [, c]) => s + c, 0);
  const kindSegments: DonutSegment[] = [
    ...byType.slice(0, TOP_KINDS).map(([type, count]) => ({ key: type, label: typeLabel(type), value: count, display: n(count) })),
    ...(otherKinds > 0 ? [{ key: "__other", label: t("kinds.other"), value: otherKinds, display: n(otherKinds), color: MUTED_SHADE }] : []),
  ];

  // Newest warning posted (ISO strings sort correctly as text).
  const newest = alerts.reduce<string | null>((m, a) => (!m || a.createdAt > m ? a.createdAt : m), null);

  const open = alerts.find((a) => a.id === openId) ?? null;
  const openLevel = open ? levelOf(open.severity) : "other";
  const openGroup = open ? todoGroup(open.type, open.title) : "general";
  const openSource = open ? extUrl(open.sourceUrl) : null;
  const openStatus = open ? statusOf(open) : null;

  /** Tap-to-call emergency numbers (112 always; 1077 for disasters; 101 for fire). */
  const callButtons = (group: string) => (
    <div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>
      <ActionLink href="tel:112" primary>
        {t("call.n112")}
      </ActionLink>
      {DISASTER_GROUPS.has(group) && (
        <ActionLink href="tel:1077">
          {t("call.n1077")}
        </ActionLink>
      )}
      {group === "fire" && (
        <ActionLink href="tel:101">
          {t("call.n101")}
        </ActionLink>
      )}
    </div>
  );

  return (
    <ModulePage>
      <PageHeader icon={Bell} title={mt.label("alerts")} description={t("description")} backHref={base} freshness={newest ? { asOf: newest } : undefined} />

      {isLoading && <LoadingShell rows={4} />}
      {error && <ErrorBlock />}

      {/* No warning: say so, and still show who to call. */}
      {!isLoading && !error && alerts.length === 0 && (
        <>
          <EmptyState title={t("empty.title", { district: districtName })} body={t("empty.body")} />
          <Card tinted padding={18} style={{ marginTop: 16 }}>
            <p className="ftp-label" style={{ margin: "0 0 10px", color: "var(--hue-deep)" }}>
              {t("call.title")}
            </p>
            {callButtons("flood")}
          </Card>
        </>
      )}

      {!isLoading && !error && alerts.length > 0 && (
        <>
          {/* 2. The answer in one sentence. */}
          <Explainer>
            {t.rich("answer", { total: live.length, district: districtName, b: bold })}{" "}
            {red + orange > 0 ? t.rich("answerSevere", { red: n(red), orange: n(orange), b: bold }) : t("answerCalm")}
            {ended > 0 && <> {t("answerEnded", { ended })}</>}
          </Explainer>

          {/* 3. Four big numbers. */}
          <StatStrip cols={4}>
            <StatTile label={t("tiles.active")} value={n(live.length)} asOf={newest} />
            <div className={LEVEL_HUE.critical} style={{ display: "grid", minWidth: 0 }}>
              <StatTile label={t("tiles.red")} value={n(red)} sub={t("level.critical.meaning")} />
            </div>
            <div className={LEVEL_HUE.high} style={{ display: "grid", minWidth: 0 }}>
              <StatTile label={t("tiles.orange")} value={n(orange)} sub={t("level.high.meaning")} />
            </div>
            <StatTile label={t("tiles.types")} value={n(byType.length)} />
          </StatStrip>

          {/* 4. The picture: one coloured circle per warning, and what the colours mean. */}
          <Card tinted padding={18} style={{ marginTop: 16 }}>
            <figure style={{ margin: 0 }}>
              <div
                role="img"
                aria-label={t("symbols.aria", { total: n(live.length), red: n(red), orange: n(orange), other: n(live.length - red - orange) })}
                style={{ display: "flex", flexWrap: "wrap", gap: 6, alignItems: "center" }}
              >
                {live.slice(0, MAX_SYMBOLS).map((a, i) => (
                  <span
                    key={a.id}
                    aria-hidden
                    className="ftp-pop"
                    style={{ display: "inline-flex", width: 36, height: 36, alignItems: "center", justifyContent: "center", borderRadius: 10, background: "var(--ftp-surface)", ["--i" as string]: i }}
                  >
                    <LevelDot level={levelOf(a.severity)} size={20} />
                  </span>
                ))}
                {live.length > MAX_SYMBOLS && (
                  <span className="ftp-num" style={{ fontSize: 13, color: "var(--hue-deep)", marginInlineStart: 4 }}>
                    {t("symbols.more", { n: n(live.length - MAX_SYMBOLS) })}
                  </span>
                )}
              </div>
              <figcaption style={{ marginTop: 12 }}>
                <p style={{ margin: "0 0 8px", fontSize: 13, lineHeight: "20px", color: "var(--ftp-text-2)" }}>{t("symbols.each")}</p>
                <ul style={{ listStyle: "none", margin: 0, padding: 0, display: "flex", flexWrap: "wrap", gap: 8 }}>
                  {LEGEND.map((l) => (
                    <li key={l} className={LEVEL_HUE[l]}>
                      <Chip>
                        <LevelDot level={l} />
                        {t("levelLabel", { name: t(`level.${l}.name`), meaning: t(`level.${l}.meaning`) })}
                      </Chip>
                    </li>
                  ))}
                </ul>
              </figcaption>
            </figure>
          </Card>

          {/* 5. One colour-coded card per warning; tap for what to do. */}
          <Section title={t("list.title")}>
            <div className="ftp-grid">
              {alerts.map((a) => {
                const lv = levelOf(a.severity);
                const st = statusOf(a);
                const range = whenText(a);
                return (
                  <div key={a.id} className={LEVEL_HUE[lv]} style={{ display: "flex", minWidth: 0 }}>
                    <TapCard
                      title={a.title}
                      titleLang={dataLang(a.title, locale)}
                      subtitle={a.titleLocal ?? undefined}
                      subtitleLang={dataLang(a.titleLocal, locale)}
                      hint={t("list.hint")}
                      onOpen={() => setOpenId(a.id)}
                      style={{
                        background: st === "ended" ? "var(--ftp-surface)" : "linear-gradient(135deg, var(--hue-tint) 0%, #fff 80%)",
                        border: `1px solid color-mix(in srgb, var(--hue) ${st === "ended" ? 15 : 45}%, var(--ftp-border))`,
                        opacity: st === "ended" ? 0.75 : 1,
                      }}
                    >
                      <span style={{ display: "flex", flexWrap: "wrap", gap: 6 }}>
                        <Chip>
                          <LevelDot level={lv} />
                          {t(`level.${lv}.name`)}
                        </Chip>
                        <Chip>{typeLabel(a.type)}</Chip>
                        {st === "ended" && a.endDate && <Chip>{t("list.ended", { date: shortDate(a.endDate) })}</Chip>}
                        {st === "upcoming" && a.startDate && <Chip>{t("list.from", { start: shortDate(a.startDate) })}</Chip>}
                        {st === "now" && range && <Chip>{range}</Chip>}
                      </span>
                      <Meta lang={dataLang(a.description, locale)} clamp={3}>
                        {a.description}
                      </Meta>
                      {a.location && (
                        <Meta lang={dataLang(a.location, locale)}>
                          {a.location}
                        </Meta>
                      )}
                      {a.autoGenerated && <Meta>{t("list.fromNews")}</Meta>}
                    </TapCard>
                  </div>
                );
              })}
            </div>
          </Section>

          {/* 6. Kinds of warning as a ring (needs two kinds to say anything). */}
          {byType.length > 1 && (
            <Section title={t("charts.title")}>
              <ChartCard
                title={t("kinds.title")}
                units={t("kinds.units")}
                simple={t.rich("kinds.simple", { type: typeLabel(byType[0][0]), n: n(byType[0][1]), total: n(alerts.length), b: bold })}
                asOf={newest}
                table={kindSegments.map((s) => ({ label: s.label, value: s.display }))}
              >
                <HueDonut segments={kindSegments} center={n(alerts.length)} centerSub={t("kinds.center")} ariaLabel={t("kinds.aria", { total: n(alerts.length) })} percentOf={pct} />
              </ChartCard>
            </Section>
          )}


          <div style={{ marginTop: 20 }}>
            <AIInsightCard module="alerts" district={district} />
          </div>
        </>
      )}

      <ModuleNews district={district} state={state} locale={locale} module="alerts" />
      <div style={{ marginTop: 28 }}>
        <PageActions
          locale={locale}
          district={district}
          moduleSlug="alerts"
          shareText={
            live.length > 0
              ? t("share", { district: districtName, total: n(live.length), red: n(red), orange: n(orange) })
              : t("shareEmpty", { district: districtName })
          }
        />
      </div>

      {/* Everything about one warning, in its colour. */}
      <DetailSheet
        open={!!open}
        onClose={() => setOpenId(null)}
        hueClassName={LEVEL_HUE[openLevel]}
        title={open?.title ?? ""}
        titleLang={open ? dataLang(open.title, locale) : undefined}
        subtitle={open?.titleLocal ? <span lang={dataLang(open.titleLocal, locale)}>{open.titleLocal}</span> : undefined}
        footer={
          open && (
            <>
              {openSource && (
                <ActionLink href={openSource} newTab>
                  {t("sheet.readNotice")}
                </ActionLink>
              )}
              <ActionLink href="tel:112" primary>
                {t("call.n112")}
              </ActionLink>
            </>
          )
        }
      >
        {open && (
          <>
            <SheetNote>
              {t.rich("sheet.levelNote", { level: t(`level.${openLevel}.name`), meaning: t(`level.${openLevel}.meaning`), b: bold })}
              {openStatus === "ended" && open.endDate && <> {t("sheet.endedNote", { date: shortDate(open.endDate) })}</>}
            </SheetNote>

            <div>
              <p lang={dataLang(open.description, locale)} className="ftp-body" style={{ margin: 0, fontSize: 15, lineHeight: "23px" }}>
                {open.description}
              </p>
              {open.descriptionLocal && (
                <p lang={dataLang(open.descriptionLocal, locale)} className="ftp-body" style={{ margin: "8px 0 0", fontSize: 15, lineHeight: "24px", color: "var(--hue-deep)" }}>
                  {open.descriptionLocal}
                </p>
              )}
            </div>

            <SheetBlock title={t("sheet.whatToDo")}>
              <ol style={{ margin: 0, paddingInlineStart: 22, display: "flex", flexDirection: "column", gap: 6, fontSize: 15, lineHeight: "22px" }}>
                {["a", "b", "c", "d"]
                  .filter((k) => t.has(`todo.${openGroup}.${k}`))
                  .map((k) => (
                    <li key={k}>{t(`todo.${openGroup}.${k}`)}</li>
                  ))}
              </ol>
            </SheetBlock>

            <DetailList
              rows={[
                { label: t("sheet.level"), value: t("levelLabel", { name: t(`level.${openLevel}.name`), meaning: t(`level.${openLevel}.meaning`) }) },
                { label: t("sheet.kind"), value: typeLabel(open.type) },
                { label: t("sheet.where"), value: open.location, lang: dataLang(open.location, locale) },
                { label: t("sheet.when"), value: whenText(open) },
                { label: t("sheet.posted"), value: <span suppressHydrationWarning>{dateTime(open.createdAt)}</span> },
                {
                  label: t("sheet.source"),
                  value: openSource ? (
                    <a href={openSource} target="_blank" rel="noopener noreferrer" style={{ color: "var(--hue-deep)" }}>
                      {hostOf(openSource)}
                    </a>
                  ) : open.autoGenerated ? (
                    t("list.fromNews")
                  ) : null,
                },
              ]}
            />

            <SheetBlock title={t("call.title")}>
              {callButtons(openGroup)}
            </SheetBlock>

            <SheetSmall>{t("sheet.follow")}</SheetSmall>
          </>
        )}
      </DetailSheet>
    </ModulePage>
  );
}

export default function AlertsPage({ params }: { params: Promise<{ locale: string; state: string; district: string }> }) {
  const mt = useModuleText();
  return (
    <ModuleErrorBoundary moduleName={mt.label("alerts")}>
      <AlertsPageInner params={params} />
    </ModuleErrorBoundary>
  );
}
